### ISSUE TITLE
IC2 reactors can explode protected areas

### ISSUE THREAD

**Issue by Eufranio** [SpongePowered/SpongeForge#1383]
I know that's a known issue with the reactors, but I think with the tracking system those explosions could be controlled. When a IC2 reactor explodes, it will break the blocks ignoring their protection, same goes for nukes and etc...

**Comment by axle2005** [comment]
GP Issue

**Comment by loveyanbei** [comment]
Resolved through decompiling the IC2 and insert event to Sponge event bus, but obviously it's not enough.
IC2 has a home-brew explosion system, bypassing NMS one.

**Comment by loveyanbei** [comment]
![img_2428](https://cloud.githubusercontent.com/assets/7147471/25414505/6a8f7f1e-2a64-11e7-8d11-d7c7161a1a52.PNG)
IC2 pushed events to forge but not captured

**Comment by Eufranio** [comment]
I believe Sponge will need to add this hardcoded check...

**Comment by ryantheleach** [comment]
FWIW ExplosionIC2 extends Explosion.

I've partially decompiled the dev versions of IC2 in an attempt to work out what events, if any, would be captured by sponge.

https://gist.github.com/ryantheleach/12d625805e2e57ba826ce3ae2024a03e

As far as I can see from decompiling the dev version of 1.12, the logic goes something like this.

1. Throw a custom explosion event that doesn't extend the forge explosion event.
2. Record all entities that are in range, and sort by distance.
2. recursively shoot rays in order to cover a large area without the dumb vanilla pattern. (whilst damaging entities??)
3. apply effects to all entities in range.
4. Iterate over y 1 layer at a time, collecting drops(as if mined without fortune), onExploding each block as it's hit.
5. itemstack merging, per item type, spawned at highest y position for each x,z,itemstacktype triplet

Yeah, with that itemstack pre-merging there is literally no way for sponge to be able to traceback / filter the entity items spawned by ic2 explosions, without events or hooks added by ic2.

the good news is, it should be possible to track them as the drops of an explosion..
so, a super super dumb plugin, could check the name of the explosion class in the cause, and deny all the item spawns

Edit: Well actually... it'd be hacky, but you could just return no drops when the block is being checked at that location, if the location is protected, and the cause of the check was an explosion... Maybe.

**Comment by ryantheleach** [comment]
After reading these 2 related issues, I believe this should at least be partially fixed, but needs to be tested on 1.12 with reactors specifcally.

Related Issues:
----
https://github.com/SpongePowered/SpongeForge/issues/1811 - IC2 Dupes blocks on explosion.
https://github.com/SpongePowered/SpongeForge/issues/1812 - IC2 Tile Entities arn't available on restore.

**Comment by Zidane** [comment]
Can you reset with latest and let us know if it is sitll happening?

**Comment by clienthax** [comment]
@Zidane still seems to be valid with IC2Classic

**Comment by gabizou** [comment]
Looking into this in the debugger, there's enough information that Sponge is passing through the `ExplosionEvent.Pre` to be able to cancel said event:

<img width="1515" alt="Screen Shot 2019-07-30 at 12 12 48 PM" src="https://user-images.githubusercontent.com/1203877/62158057-77d00880-b2c3-11e9-9a1e-6ac5882ba9f1.png">

I'd say it's an issue with GriefPrevention's cause stack check not involving range, or owner of the `TileEntity` that is directly causing the explosion. It is however verifying that the `Player` [is in the cause](https://github.com/MinecraftPortCentral/GriefPrevention/blob/ff7d1aac63b6a2267cb31359f04429a851a08d72/src/main/java/me/ryanhamshire/griefprevention/util/CauseContextHelper.java#L66), but the [location check is not taking size into account](https://github.com/MinecraftPortCentral/GriefPrevention/blob/ff7d1aac63b6a2267cb31359f04429a851a08d72/src/main/java/me/ryanhamshire/griefprevention/listener/EntityEventHandler.java#L144-L146) if the explosion is going to end up entering a claim.

**Comment by IteratorW** [comment]
It's still working. 
```
    Minecraft: 1.12.2
    SpongeAPI: 7.1.0-13da4949c
    Sponge: 1.12.2-7.1.7-SNAPSHOT
    SpongeForge: 1.12.2-2838-7.1.7-RC3924
    Minecraft Forge: 14.23.5.2838
    JVM: 1.8.0_201/64-bit (Oracle Corporation)
    OS: Linux (3.10.0-862.14.4.el7.x86_64/amd64)

    IC2 ver: industrialcraft-2-2.8.109-ex112
```

When industrial TNT (or anything else) explodes near a protected area, the explosion does not occur, but explosion drop is created.

**Comment by ImMorpheus** [comment]
> Looking into this in the debugger, there's enough information that Sponge is passing through the ExplosionEvent.Pre to be able to cancel said event:

What about ChangeBlockEvent ?

I've tried to reproduce the issue with SF and `industrialcraft-2-2.8.187-ex112`:

Code to reproduce:

```
    @Listener
    public void onBreak(ChangeBlockEvent.Break event) {
        event.setCancelled(true);
    }
```

I let an industrial TNT explode and the blocks dropped without breaking (dupe), plus the tnt wasn't disappearing. It kept on exploding.

Note: I have not investigated the issue and even if this doesn't seem the expected behaviour, I don't know if it can be fixed on our side.

**Comment by IteratorW** [comment]
Can this thing be fixed via IC2 patch? I want to make one.
