### ISSUE TITLE
world/data/scoreboard.dat not updated when using SpongeForge

### ISSUE THREAD

**Issue by diluvium** [SpongePowered/SpongeForge#1400]
I've been trying to add a death counter to the tab screen when using spongeforge-1.11.2-2227-6.0.0-BETA-2260.jar

commands 

> scoreboard objectives add Deaths deathCount
[20:07:34] [Server thread/INFO]: Added new objective 'Deaths' successfully
> scoreboard objectives setdisplay list Deaths
[20:07:45] [Server thread/INFO]: Set the display objective in slot 'list' to 'Deaths'

With SpongeForge installed, the scoreboard.dat isn't updated, neither after the commands are entered nor when the server is stopped, so the death counter doesn't persist. Without Sponge, the appropriate entries are added to the file, and the death counter is there after a restart..

**Comment by Autopoietico** [comment]
This happens also for teams, and other info saved in the scoreboard file, the only scoreboard that don't reset when server is stopped is tags, maybe because this is stored in the indivual player.dat file.

**Comment by Flashback083** [comment]
Hello, i have the same problem, also there is any fix atm ? Thanks !

**Comment by Aaron1011** [comment]
Sorry for the excessively long delay in getting to this. It should be fixed in the latest SpongeForge.

For reference, the issue was first introduced in https://github.com/SpongePowered/SpongeCommon/commit/092d4cb2f5f56f93f90e6730623d88797f77e33b#diff-851d4e94ff55a5d4a5e26f97ac746111R294.

**Comment by Flashback083** [comment]
I test the spongeforge-1.10.2-2281-5.2.0-BETA-2401.jar version but its seems doesnt work, i need to delete scoreboard.dat before the update ?
Sorry ^^'

**Comment by phit** [comment]
the fix was only applied for 1.11 and 1.12 by the looks of it, backport? @Aaron1011 

~~edit: actually the 1.12 version didn't pass [travis](https://travis-ci.org/SpongePowered/SpongeForge/builds/245671737?utm_source=github_status&utm_medium=notification), so the fix is only out for 1.11 right now~~
fix is still missing for stable-5
