### ISSUE TITLE
Unexpected World Change Detected

### ISSUE THREAD

**Issue by Keaton1188** [SpongePowered/SpongeForge#1895]
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2555-7.0.0-BETA-2765.jar
- Forge version: 14.23.1.2555
- Java version: OpenJDK 64-Bit Server VM (build 25.121-b13, mixed mode)
- Operating System: CentOS 6.8 (Final)

- Plugins/Mods:
DW20 1.12 Modpack

**Issue Description**
Seem to be getting a lot of spam related to a unexpected world change:
https://gist.github.com/Keaton1188/29e4107e1e3b2fc4ea615b73300e3504

**Comment by JoeSGT** [comment]
can you tried this with spongeforge-1.12.2-2555-7.0.0-BETA-2766

**Comment by phit** [comment]
@JoeSGT 2766 just changed some logging

**Comment by JoeSGT** [comment]
ohh okay sorry i just though it might help cause there was another commit related about reduce spamming

**Comment by phit** [comment]
oh yeah it will help the spam, just not fix the underlying issue ;)

**Comment by alicheek** [comment]
Tbh there doesnt seem to be much change in the logging still showing up quite a few times on our logs having said that at least we arent getting like 500 MB logs any more!

**Comment by phit** [comment]
@alicheek make sure verbose is set to `false` in your global.conf

**Comment by Keaton1188** [comment]
Yep, we have; verbose=false and verbose-errors=false

**Comment by Kraziebone116** [comment]
Getting the same spam to console as listed above in the original post.

We updated to:
 - spongeforge-1.12.2-2555-7.0.0-BETA-2779.jar

furthermore we updated to the newest build as well to see if it got any better, but it did not:
 - spongeforge-1.12.2-2555-7.0.0-BETA-2783.jar

Currently running:
- Java version 1.8.0_131
- Forge version 1.12.2-14.23.1.2555
- CentOS release 6.9 (Final)
- DW20 1.12 Modpack

**Comment by gabizou** [comment]
should be fixed in latest

**Comment by phit** [comment]
@Keaton1188 still an issue in latest?

**Comment by Keaton1188** [comment]
Not able to test on latest version yet as newest sponge version breaks a plugin of ours, dev can't fix it till Jan 3rd so gotta wait.

**Comment by Keaton1188** [comment]
@phit The issue in the first Gist I put seems to be sorted but going through fml log I see we are still getting some spam; https://gist.github.com/Keaton1188/577d7fea3c31ff150f26aae2a8ccbc7c

Believe it may be already reported, not 100%

**Comment by Keaton1188** [comment]
Yea.. I reported it :P 

I'll close this.
