### ISSUE TITLE
RealisticItemDrops /give command drops an extra item

### ISSUE THREAD

**Issue by se7enek** [SpongePowered/SpongeForge#2757]
**I am currently running**
- SpongeForge version:  1.12.2.-2825-7.1.6-RC3708
- Forge version: 1.12.2-14.23.5.2815
- Java version: latest (1.8.0)
- Operating System: Centos7

**Plugins and Mods Im using**
- Plugins/Mods:
No plugins installed.
Modpack: Sevtech 3.1.1

**Issue Description**
Simple enough. /give command gives extra 1 item. 
Ill simplify commands:
/give cobble 1 - Adds 1 cobble to inventory + 1 extra drops from player (that can be picked up)
/give cobble 5 - Adds 5 cobble to inventory + 1 extra drops...

Whatever amount is, it always drops 1 extra of item. 

Server log doesnt contain any information beside:
 [PLAYER: Given [Cobblestone] * 1 to PLAYER]

After installing JEI, Clicking item in JEI with CheatMode, it gives properly just 1 item. No extras.

**Comment by se7enek** [comment]
Made some more testing about that.
1. Downloaded Sevtech Pack and ran server
- Giving items give just 1 item, no extra drops.
2. Removed FoamFix mod entirely and ran server
- Giving items still give just 1 item with no extra drops
3. Added SpongeForge v. 1.12.2.-2825-7.1.6-RC3708 and ran server
- Giving items drops extra 1 "piece" on ground in front of player.

So i assume its Sponge-Related issue.

**Comment by CaptainSisko** [comment]
I have done some testing on my SevTech server running 1.12.2-2825-7.1.6-RC3711 and i can definitely replicate this issue but only if i rename my plugins folder so none load. I have however tested with CatClearLag and Nucleus and the issue still occurs. I am still going through my plugins to find out which one stops the issue from occurring.

If you make a client with no mods but with Sponge, the issue does not occur. That means it is likely a mod from SevTech causing it. I will do some testing later to try and find which mod it is.

Im not entirely sure if this is related but if you do the /give command in singleplayer (without sponge) you can see that the item doesnt go directly into your inventory, it is spawned right on top of you and you pick it up. That doesnt normally happen so i think a mod in SevTech may be doing that.

**Comment by se7enek** [comment]
Not entirely mod itself, more like both conflict between mod and sponge.
Got any ideas which mod may cause that?

And, you said u cant reproduce this without renaming plugins folder? Aka, WITH your plugins, bug doesnt occur? Could i have a list of ur plugins? That fix is satisfying for me ;p

**Comment by CaptainSisko** [comment]
Yeah sorry thats what i meant, a mod compatibility issue with sponge.

To make what i initially said clearer, in order to reproduce this issue, i had to remove all plugins. One of the plugins i have is stopping this issue from occurring, i am just unsure which one at the moment as i haven't had a chance to do some further testing. If i find out, ill let you know which one it is so you can use that as a workaround.

I am about to do some more testing that should hopefully tell me which mod is causing the issue.

**Comment by johnfriedrich** [comment]
That one extra drop is the visual drop that is produced and you can see for a half a second when using /give. Somehow this gets added to the inventory aswell. This was in an issue with sponge years ago during 1.10.2, can't find the ticket sadly

**Comment by se7enek** [comment]
Yeah i was recently starting to configure server, yet after setting most of the stuff up, was time to test and that happened xD

Im literally going crazy about it right now cause i use /give everywhere ... Votes, Crates, MenuShop, Advancements Rewards... 

@CaptainSisko you could provide me list of all the plugins u use so i can try adding them one by one or all, and basically check, so i could help ;)

**Comment by se7enek** [comment]
Not much but... When you are full inventory and u use /give cobble 1, only 1 will drop in front of u - no extras. So i assume it has something to do with "stacking" items on floor. Like it is stacked "on the fly" but 1 drops cuz some bug. I assume the plugin that was "fixing" it, was the one optimizing server a bit by stacking faster or disabling entity stacking at all.

**Comment by se7enek** [comment]
@CaptainSisko 
I removed "Realistic Item Drops" mod from server and it no longer "duplicates" given item. So its kinda workind workaround, however would really love to check list of your plugins, cause this mod was looking really good to use ;P

**Comment by ghost** [comment]
This seems to be a Mod-related issue, nothing really to do with SpongeForge.
The issue has already been reported to the Mod Developer. You can see this below.

https://github.com/Funwayguy/RealisticItemDrops/issues/16

**Comment by CaptainSisko** [comment]
@se7enek Sorry it has taken me so long to get back to you, i have been busy with work and haven't had the chance to look into this further.

I did some limited testing on my SevTech test server the other day but dont have any conclusive results just yet as to which plugin i'm using that is preventing this issue from occurring.

The list isn't very long so it shouldn't take *too* long to test each one. Ill try to do some more testing tonight. 

I am currently using:
```
CatClearLag
FastAsyncWorldEdit
GriefPrevention
LuckPerms
MagiBridge
MMCReboot
MMCTickets
Nucleus
Tattle
YourCustomPaintings
```

I see from the ticket that 0xEviqnn linked to that the issue is known by the RealisticItemDrops dev, he does say that he has fixed the issue in the past but other mods keep breaking it. 

Seeing as this issue doesn't occur without Sponge installed, its likely not one of the mods in SevTech conflicting with RealisticItemDrops, but Sponge. (However it is possible that Sponge is conflicting with a mod other than RealisticItemDrops which is in turn breaking RealisticItemDrops)

At this point i think your workaround of removing RealisticItemDrops is the best course of action for anyone experiencing this issue.

**Comment by se7enek** [comment]
After checking list of your plugins, i may rule out couple of these, as im using them too:

`GriefPrevention
LuckPerms
MagiBridge
MMCReboot
MMCTickets
Nucleus`

so this brings us to any of following plugins (that may "fix" the bug:

`CatClearLag
FastAsyncWorldEdit
Tattle
YourCustomPaintings`

And because i dont have any entity clearing plugin, i would say its best bet in there. Will check these tomorrow and update the topic.

**Comment by se7enek** [comment]
Funny enough, i tried installing every single plugin you provided, and i can still experience same issue. None of plugins help me out with that.

**Comment by gabizou** [comment]
Can you re-test with latest? There might have been an awkward drops bug fixed with custom item drops, but I'm not sure if it directly impacted this issue.

**Comment by phit** [comment]
@se7enek did you have any chance to retest yet?

**Comment by se7enek** [comment]
I am currently not at home. Will be back at friday.

**Comment by phit** [comment]
still throwing an extra item on the ground
spongeforge-1.12.2-2838-7.1.7-RC3807.jar
RealisticItemDrops-1.2.14.jar

**Comment by ImMorpheus** [comment]
Not able to reproduce on SF (Updated to https://github.com/SpongePowered/SpongeForge/commit/f5f23d3ede4ff547b75b0d36e785869288df36ee)
SC updated to https://github.com/SpongePowered/SpongeCommon/commit/5e14cffe5bac9c358d1ef0c444d247680c9a8cb7

RealisticItemDrops-1.2.14.jar
