### ISSUE TITLE
[1.12.2 2838]i have i no idea why this happens

### ISSUE THREAD

**Issue by tmvkrpxl0** [SpongePowered/SpongeForge#2840]
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2838-7.1.7-RC3818
- Forge version: 2838
- Java version: OpenJDK 64-Bit Server VM (Zulu 8.36.0.1-CA-win64) (build 25.202-b05, mixed mode)
- Operating System:Windows 10

- Plugins/Mods:
Plugins: Luckperms, Nucleus
Mods: ```
AE-Net-Vis-Tool-1.12.2-1.0.3.0-universal.jar                   ProjectRed-1.12.2-4.9.1.92-Base.jar
 AE2WTLib-1.12.2-1.0.6.jar                                      ProjectRed-1.12.2-4.9.1.92-compat.jar
 ActuallyAdditions-1.12.2-r148.jar                              ProjectRed-1.12.2-4.9.1.92-fabrication.jar
 Advanced+Machines-61.0.1.jar                                   ProjectRed-1.12.2-4.9.1.92-integration.jar
 Advanced+Solar+Panels-4.3.0.jar                                ProjectRed-1.12.2-4.9.1.92-lighting.jar
 AgriCraft-2.12.0-1.12.0-a6.jar                                 ProjectRed-1.12.2-4.9.1.92-mechanical.jar
 AnvilFix-1.12.2-1.0.3.jar                                      ProjectRed-1.12.2-4.9.1.92-world.jar
 AppleCore-mc1.12.2-3.2.0.jar                                   Psi-r1.1-76.jar
 Arcane+Essentials-0.9.jar                                      PsiAddons-1.1.05.jar
 Aroma1997Core-1.12.2-2.0.0.2.b165.jar                          RebornCore-1.12.2-3.13.12.447-universal.jar
 Aroma1997s-Dimensional-World-1.12.2-2.0.0.2.b96.jar            RedstoneArsenal-1.12.2-2.6.3.18-universal.jar
 Atomic-Science-1.12.2-3.2.0b105.jar                            RedstoneFlux-1.12-2.1.0.6-universal.jar
 AutoRegLib-1.3-30.jar                                          Reliquary-1.12.2-1.3.4.786.jar
 Avaritia-1.12.2-3.3.0.33-universal.jar                         ResourceLoader-MC1.12.1-1.5.3.jar
 Baubles-1.12-1.5.2.jar                                         SeedsForWizardry+1.0+For+MC+Forge+1.12.2.jar
 BetterFps-1.4.8.jar                                            SimplyJetpacks2-1.12.2-2.2.12.65.jar
 BiomesOPlenty-1.12.2-7.0.1.2441-universal.jar                  SplashAnimation-0.2.1.jar
 BloodArsenal-1.12.2-2.2.0-28.jar                               StackUp-0.2.3.jar
 BloodMagic-1.12.2-2.4.1-103.jar                                StevesCarts-1.12.2-2.4.30.134.jar
 Botania+r1.10-361.jar                                          TechReborn-1.12.2-2.22.1.979-universal.jar
 BotanicAdditions-1.12.2-2r.jar                                 Tesla-1.12.2-1.0.63.jar
 BrandonsCore-1.12.2-2.4.12.205-universal.jar                   TexFix+V-1.12-4.0.jar
 CTM-MC1.12.2-0.3.3.22.jar                                      Thaumcraft-1.12.2-6.1.BETA26.jar
 ChickenASM-1.12-1.0.2.7.jar                                    ThaumicComputers-MC1.12.2-0.4.4.jar
 Chisel-MC1.12.2-0.2.1.35.jar                                   ThermalCultivation-1.12.2-0.3.3.12-universal.jar
 ChiseledAdditions-1.0.0.jar                                    ThermalDynamics-1.12.2-2.5.5.21-universal.jar
 CoFHCore-1.12.2-4.6.3.27-universal.jar                         ThermalExpansion-1.12.2-5.5.4.43-universal.jar
 CoFHWorld-1.12.2-1.3.1.7-universal.jar                         ThermalFoundation-1.12.2-2.6.3.27-universal.jar
 CodeChickenLib-1.12.2-3.2.2.353-universal.jar                  ThermalInnovation-1.12.2-0.3.3.12-universal.jar
 CommonCapabilities-1.12.2-2.4.1.jar                            UniDict-1.12.2-2.9.2.jar
 Computronics-1.12.2-1.6.6.jar                                  UnlimitedChiselWorks-0.2.1.jar
 CraftTweaker2-1.12-4.1.18.jar                                  VanillaFix-1.0.10-99.jar
 Cucumber-1.12.2-1.1.3.jar                                      WailaHarvestability-mc1.12-1.1.12.jar
 CustomMainMenu-MC1.12.2-2.0.9.jar                              WanionLib-1.12.2-2.2.jar
 Cyclic-1.12.2-1.19.11.jar                                      Wawla-1.12.2-2.5.273.jar
 CyclopsCore-1.12.2-1.3.0.jar                                   WirelessCraftingTerminal-1.12.2-3.11.88.jar
 Draconic-Additions-1.12.2-1.7.1.17-universal.jar               WorldControl-1.0.31.jar
 Draconic-Evolution-1.12.2-2.3.22.343-universal.jar             WrapUp-1.12-1.1.3.jar
"Electroblob's+Wizardry+-+4.1.4+-+MC+1.12.2.jar"                XCPatch-1.12.2-1.0.1.jar
 EnderCore-1.12.2-0.5.57.jar                                    YNot-0.2.4.jar
 EnderIO-1.12.2-5.0.44.jar                                      ae2stuff-0.7.0.4-mc1.12.2.jar
 EnderIO-endergy-1.12.2-5.0.44.jar                              aiotbotania-0.7.jar
 EquivalentAdditions-1.12.2-7r.jar                              alternatingflux-0.12.2-2.jar
 ExpandedEquivalence-1.12.2-12r.jar                             appliedenergistics2-rv6-stable-6.jar
 ExtraBotany-r1.1-53-fix.jar                                    astralsorcery-1.12.2-1.10.19.jar
 ExtraCells-1.12.2-2.6.2a.jar                                   bdlib-1.14.3.12-mc1.12.2.jar
 ExtraPlanets-1.12.2-0.5.2.jar                                  botanianeedsit-1.12.2-2.1-release.jar
 ExtraSpells-1.12.2-1.0.7.jar                                   buildcraft-all-7.99.24.1.jar
 ExtremeReactors-1.12.2-0.4.5.66.jar                            environmentaltech-1.12.2-2.0.20.1.jar
 FTBLib-5.4.1.99.jar                                            extraalchemy-0.3.8.6.1-release.jar
 FTBUtilities-5.4.0.96.jar                                      extrautils2-1.12-1.9.9.jar
 FastFurnace-1.12.2-1.3.1.jar                                   fluxnetworks-1.12.2-3.0.19-21.jar
 FastWorkbench-1.12.2-1.7.2.jar                                 foamfix-0.10.5-1.12.2.jar
 FenceJumper-1.14-1.0.1.jar                                     forestry_1.12.2-5.8.1.322.jar
 Forbidden+Magic-1.7.10-0.575.jar                               gases-1.12.2-2.0.0-pre1.jar
 ForgeMultipart-1.12.2-2.6.1.81-universal.jar                   gasesframework-1.12.2-2.0.0-pre1.jar
 Forgelin-1.8.2.jar                                             iChunUtil-1.12.2-7.2.1.jar
 GasConduits-1.12.2-1.2.1.jar                                   immersivepetroleum-1.12.2-1.1.9.jar
 GravityGun-1.12.2-7.0.1.jar                                    immersivetech-1.12-1.3.10.jar
 Guide-API-1.12-2.1.8-63.jar                                    industrialcraft-2-2.8.157-ex112.jar
 HammerCore-1.12.2-2.0.4.7.jar                                  industrialforegoing-1.12.2-1.12.12-236.jar
 Hwyla-1.8.26-B41_1.12.2.jar                                    infinitylib-1.12.0.jar
 ImmersiveCables-1.12.2-1.3.2.jar                               iridiumsource-2.0.1.jar
 ImmersiveEngineering-0.12-89.jar                               ironchest-1.12.2-7.0.64.843.jar
 IndustrialWires-1.7-36.jar                                     jei_1.12.2-4.15.0.279.jar
 InventoryTweaks-1.64+dev.146.jar                               jepb-1.12-1.2.1.jar
 ItemBlacklist-1.4.1.jar                                        journeymap-1.12.2-5.5.5b7.jar
 JAOPCA-1.12.2-2.2.8.102.jar                                    koreanchat-creo-1.12-1.9.jar
 JAOPCAAdditions-1.12.2-2.2.1.9.jar                             librarianlib-1.12.2-4.19.1-release.jar
 JAOPCAAgriculture-1.12.2-1.2.1.13.jar                          malisiscore-1.12.2-6.5.1.jar
 JustEnoughEnergistics-1.12.2-1.0.6.jar                         malisisdoors-1.12.2-7.3.0.jar
 JustEnoughIDs-1.0.2-26.jar                                     maxpotidext-0.0.2.1.jar
 JustEnoughPetroleum-0.1.jar                                    mcjtylib-1.12-3.5.3.jar
 JustEnoughResources-1.12.2-0.8.5.27.jar                        mekatweaker-1.12-1.1.2.jar
 LambdaLib2-0.1.8.jar                                           ocdevices-snapshot_20190228.jar
 LootBags-1.12.2-2.5.8.5.jar                                    oceio-1.12.2-1.0.002.jar
 MCMultiPart-2.5.3.jar                                          p455w0rdslib-1.12.2-2.1.44.jar
 MJRLegendsLib-1.12.2-1.1.8.jar                                 plumedbelt-1.0.1.jar
 MagicalPsi-1.3.2.jar                                           questionablyimmersive-1.12.2-0.1.0.jar
 ManaVisualizer-r1.0-1.jar                                      railcraft-12.0.0.jar
 Mekanism-1.12.2-9.7.5.376.jar                                  randomtweaks-1.12.2-2.5.0.6.jar
 MekanismGenerators-1.12.2-9.7.5.376.jar                        redstonepaste-mc1.12-1.7.5.jar
 MekanismJEIFix-1.12.2-1.0.0.jar                                rftools-1.12-7.71.jar
 MekanismTools-1.12.2-9.7.5.376.jar                             rftoolsdim-1.12-5.71.jar
 MrTJPCore-1.12.2-2.1.3.35-universal.jar                        rftoolspower-1.12-1.2.0.jar
 MysticalAgradditions-1.12.2-1.3.2.jar                          sampler-1.84.jar
 MysticalAgriculture-1.12.2-1.7.5.jar                           sonarcore-1.12.2-5.0.19-20.jar
 NaturalPledge-r3.0.3.jar                                       tesla-core-lib-1.12.2-1.0.15.jar
 NuclearCraft-2.16f-1.12.2.jar                                  thaumicenergistics-2.2.2.jar
 OpenComputers-MC1.12.2-1.7.4.153.jar                           thaumictinkerer-1.12.2-5.0-353c71c.jar
 OpenGlasses-MC1.12.2-1.5.5.jar                                 titlechanger-1.1.3.jar
 OpenPython-MC1.12.2-OC1.7-1.0.1.jar                            trm-b2.jar
 OptiFine_1.12.2_HD_U_E3.jar                                    twilightforest-1.12.2-3.8.689-universal.jar
"Pam's+HarvestCraft+1.12.2zc+The+7mm+Kidney+Stone+Update.jar"   valkyrielib-1.12.2-2.0.20.1.jar
 PortalGun-1.12.2-7.1.0.jar                                     xnet-1.12-1.8.1.jar
 ProjectE-1.12.2-PE1.4.1.jar                                    zerocore-1.12.2-0.1.2.8.jar
 ProjectEIntegration-1.12.2-2.2.13.jar                       foamfix-0.10.5-1.12.2.jar```

**Issue Description**
i have no idea why this happens
i never seen this kind error
i don't even know what error is.
i have lots of mods installed, but they're working fine on client
i used this JVM argument:
`java -Dfile.encoding=UTF8 -Xmx9G -Xms1G -Dsun.rmi.dgc.server.gcInterval=2147483646 -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -XX:UseSSE=4 -XX:ParallelGCThreads=2 -XX:+UseFastAccessorMethods -XX:+AggressiveOpts -XX:+DisableExplicitGC -XX:+UseAdaptiveGCBoundary -XX:SurvivorRatio=16 -server -jar forge-1.12.2-14.23.5.2838-universal.jar`

server full log(it's too long, so log is cutted out): https://del.dog/wovubabafu.rb
crash log: https://del.dog/nayomudame.rb

**Comment by tmvkrpxl0** [comment]
i used 1.12.2-2838-7.1.7-RC3800 and it worked, but it i think this should be fixed next release, so i'll keep open this issue

**Comment by KorewaLidesu** [comment]
> ---- Minecraft Crash Report ----
WARNING: coremods are present:
  SpongeCoremod (aaaa.jar)
  MekanismCoremod (Mekanism-1.12.2-9.7.5.376.jar)
  CorePlugin (LambdaLib2-0.1.8.jar)
  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.5-1.12.2.jar)
  AppleCore (AppleCore-mc1.12.2-3.2.0.jar)
  HCASM (HammerCore-1.12.2-2.0.4.7.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.64+dev.146.jar)
  TransformerLoader (OpenComputers-MC1.12.2-1.7.4.153.jar)
  NWRTweak (redstonepaste-mc1.12-1.7.5.jar)
  AdvancedRocketryPlugin (AdvancedRocketry-1.12.2-1.5.0-139-universal.jar)
  JEIDLoadingPlugin (JustEnoughIDs-1.0.2-26.jar)
  ForgelinPlugin (Forgelin-1.8.2.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-89.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.57-core.jar)
  Max Potion ID Extender (maxpotidext-0.0.2.1.jar)
  MekanismJEIFix (MekanismJEIFix-1.12.2-1.0.0.jar)
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.210.jar)
  AstralCore (astralsorcery-1.12.2-1.10.19.jar)
  LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  CoreMod (Aroma1997Core-1.12.2-2.0.0.2.b165.jar)
Contact their authors BEFORE contacting forge
// There are four lights!
Time: 6/26/19 12:55 AM
Description: Exception in server tick loop
java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
net/minecraft/world/gen/ChunkProviderServer.func_186025_d(II)Lnet/minecraft/world/chunk/Chunk; @182: invokespecial
  Reason:
    Type 'java/lang/Object' (current frame, stack[10]) is not assignable to 'net/minecraft/world/gen/ChunkProviderServer'
  Current Frame:
    bci: @182
    flags: { }
    locals: { 'net/minecraft/world/gen/ChunkProviderServer', integer, integer, 'net/minecraft/world/chunk/Chunk', long, long_2nd, 'java/lang/Throwable', 'net/minecraft/crash/CrashReport', 'net/minecraft/crash/CrashReportCategory', 'java/lang/Object', integer, integer }
    stack: { 'net/minecraft/world/gen/ChunkProviderServer', integer, integer, 'org/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable', 'net/minecraft/world/chunk/Chunk', long, long_2nd, 'java/lang/Throwable', 'net/minecraft/crash/CrashReport', 'net/minecraft/crash/CrashReportCategory', 'java/lang/Object', integer, integer }
  Bytecode:
    0x0000000: 2a1b 1c36 0b36 0a3a 092a 1909 150a 150b
    0x0000010: b701 054e 2dc7 00d9 1b1c 2a1b 1cbb 0107
    0x0000020: 5913 0108 03b7 0109 b701 0db8 0094 3704
    0x0000030: 2ab4 0059 1b1c 360b 360a 3a09 2a19 0915
    0x0000040: 0a15 0bb7 0111 4ea7 007c 3a06 1906 1301
    0x0000050: 13b8 0119 3a07 1907 1301 1bb6 011f 3a08
    0x0000060: 1908 1301 2113 0123 05bd 0005 5903 1bb8
    0x0000070: 00c0 5359 041c b800 c053 b801 29b6 012f
    0x0000080: 1908 1301 3116 04b8 00b3 b601 2f19 0813
    0x0000090: 0133 2ab4 0059 b601 2f2a 1b1c bb01 0759
    0x00000a0: 1301 0803 b701 092d 1604 1906 1907 1908
    0x00000b0: 1909 150a 150b b701 37bb 0139 5919 07b7
    0x00000c0: 013c bf2a b400 4416 042d b900 d904 0057
    0x00000d0: 2db6 00dc 2d2a 2ab4 0059 b600 e02a 1b1c
    0x00000e0: bb01 0759 1301 0803 b701 09b7 013f 2db0
    0x00000f0:                                        
  Exception Handler Table:
    bci [48, 71] => handler: 74
  Stackmap Table:
    full_frame(@74,{Object[#2],Integer,Integer,Object[#131],Long,Top,Top,Top,Object[#5],Integer,Integer},{Object[#257]})
    full_frame(@195,{Object[#2],Integer,Integer,Object[#131],Long,Top,Top,Top,Object[#327],Integer,Integer},{})
    full_frame(@238,{Object[#2],Integer,Integer,Object[#131],Top,Top,Top,Top,Top,Object[#5],Integer,Integer},{})
	at net.minecraft.world.WorldServer.func_72970_h(WorldServer.java:848)
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:118)
	at org.spongepowered.common.world.WorldManager.createWorldFromProperties(WorldManager.java:844)
	at org.spongepowered.common.world.WorldManager.loadAllWorlds(WorldManager.java:812)
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:3553)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:270)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Thread.java:748)

**Comment by KorewaLidesu** [comment]
The problem is on the code 
Actually is on ChunkProviderServer

**Comment by phit** [comment]
update librarianlib
