### ISSUE TITLE
[1.10.2] Incompatibility with Morpheus mod?

### ISSUE THREAD

**Issue by Eufranio** [SpongePowered/SpongeForge#830]
https://github.com/Quetzi/Morpheus/issues/21

**Comment by gabizou** [comment]
Sounds like `PlayerDimensionChangeEvent` isn't being thrown from a [cursory glance](https://github.com/Quetzi/Morpheus/blob/master/src/main/java/net/quetzi/morpheus/helpers/MorpheusEventHandler.java#L48).

**Comment by Eufranio** [comment]
Happens here when there is only one player in the server, and he goes from overworld to another dimension (like Nether)

**Comment by FiveEYZ** [comment]
this issue just appeared for me

we were 3 people on the server and all of us went to the end

when 1 of us did a /spawn (command from nucleus) this happen: https://gist.github.com/FiveEYZ/fcd39b0aca1c27814eaecd69befe689b

i know it dosen't show any "sponge" in the crash but i think its related to all the dimension changes that were made recently

**Comment by bloodmc** [comment]
@Eufranio Please test this issue with latest build.

**Comment by bloodmc** [comment]
reopen if this is still an issue.

**Comment by Brend-Smits** [comment]
Can confirm this is an issue again after upgrading to the latest SpongeForge. 
@bloodmc is it possible due to tracker changes? Or unrelated?

**Comment by Eufranio** [comment]
Latest here, no crashes. Maybe a modpack problem? My modpack: [MagiBeta Pack](https://www.technicpack.net/modpack/magibeta-pack.940049).

**Comment by Brend-Smits** [comment]
Occured after switching to latest SF on Sky Factory 3 and on FTB Beyond

**Comment by LemADEC** [comment]
Issue is reproduced with
forge-1.10.2-12.18.3.2254-universal.jar
Morpheus-1.10.2-3.1.12.jar
VoidCraft-1.10.2-0.17.8.jar
spongeforge-1.10.2-2254-5.2.0-BETA-2259.jar

It wasn't present (?) with
spongeforge-1.10.2-2254-5.2.0-BETA-2254.jar

**Comment by Quetzi** [comment]
@Rubbertjuh The mod is all rights reserved, you do not have permission to redistribute. Any 'fix' you make to the mod would break functionality. This is on Sponge to fix.

**Comment by Brend-Smits** [comment]
@Quetzi Sorry I did not know that, can't find the license anywhere. - Edited the comment to remove the "fix"

**Comment by waggz81** [comment]
Here is the latest in multiple similar crash reports: https://pastebin.com/tszqDWPP

spongeforge-1.10.2-2281-5.2.0-BETA-2274.jar
forge-1.10.2-12.18.3.2281-universal.jar
Morpheus-1.10.2-3.1.13.jar

FTB Beyond 1.5.3 modpack

I've just disabled Morpheus on the server for now, but would like to see this issue resolved in order to enable it again, as it's quite convenient for the players and sorely missed.

Alternatively, if this issue is too involved to fix, perhaps the functionality can be added directly to Sponge?

**Comment by FiveEYZ** [comment]
I grew tired of this crash and just disabled Morpheus and installed https://ore.spongepowered.org/Icohedron/Sleep-Vote

**Comment by tolly765** [comment]
@FiveEYZ may I ask how you disabled it? We're thinking about doing the same as well, since it is still present after multiple pack updates. Not using sponge isn't an option for us either.

**Comment by LJack2k** [comment]
Remove it from the mod folder. And yes you have to do it with a pack update.

**Comment by tolly765** [comment]
Was gonna say, the last time we did something like that, it crippled people's ability to connect. Guess it isn't one of _those_ mods then. Thanks

**Comment by brandon3055** [comment]
@Quetzi Regardless of whos fault this is it could be easily fixed will a single check in your event handler. It would at the very least stop all the crashes.

**Comment by tolly765** [comment]
@brandon3055 His response to that was the fact that "it'd be redundant" and so it wasn't necessary. It is clearly necessary seeing as it is affecting a great number of people, but Quetzi doesn't want to write a few lines of code to write a "redundant" check. 

I mean, what else is there to use? Bukkit is currently under a DMCA so that's out of the question, and other alternatives simply do not have any plugins for them.

**Comment by Zidane** [comment]
@tolly7654 @brandon3055 Can I get a stacktrace with latest SpongeForge (1.10.2) and that mod? I'm going to look into fixing this.

**Comment by tolly765** [comment]
Sorry for the slow reply @Zidane, but here it is: https://pastebin.com/tPwYiERF

**Comment by Zidane** [comment]
@tolly7654 

Are you using an old build of his mod? Line 28 points to a comment and no code lol:

https://github.com/Quetzi/Morpheus/blob/master/src/main/java/net/quetzi/morpheus/helpers/SleepChecker.java#L28

**Comment by Zidane** [comment]
Oh wait, 1.10.2...keep forgetting this:

https://github.com/Quetzi/Morpheus/blob/1.10.2/src/main/java/net/quetzi/morpheus/helpers/SleepChecker.java#L28

**Comment by tolly765** [comment]
We updated a couple days ago to the latest one, so it's fine

**Comment by Zidane** [comment]
@tolly7654 

What is the quickest way to reproduce?

**Comment by tolly765** [comment]
@Zidane Get a draconic dislocator (advanced or regular), make a waypoint in the end then go to the overworld and try go to the end with it. Repeat until crash

**Comment by tolly765** [comment]
@Zidane Any update on the possible fix?

**Comment by HeberonYT** [comment]
@Zidane  The easiest and fastest way to reproduce it is to create a voidcraft portal, to enter it and to close the server immediately.
view #1635

**Comment by phit** [comment]
Still an issue in 1.11.2, tested with
>jei_1.11.2-4.5.0.291.jar
>Morpheus-1.11.2-3.2.14.jar
>spongeforge-1.11.2-2393-6.1.0-BETA-2471.jar
>TamModized-1.11.2-0.9.2.jar
>VoidCraft-1.11.2-0.19.6.jar

**Reproduction**
Installed Voidcraft since its portal seem to trigger it 100% of the time you use it.
* give yourself a Voidcraft portal
* stand in it
* be teleported
* crash happens

**Logs**
crash report https://gist.github.com/phit/d3d336f941a2e4c098188b8f9bd5e445
fml-client-latest.log https://gist.github.com/phit/2bcbb89188b3f2f2ca5495ec00aa5fba
