### ISSUE TITLE
[1.10.2] Minecraft not loads with latest AE2 nightly build and SpongeForge.

### ISSUE THREAD

**Issue by mrapplexz** [SpongePowered/SpongeForge#966]
Minecraft not loads with latest AE2 nightly build and SpongeForge.
Forge version: 1.10.2-12.18.2.2107.
Sponge version: 1.10.2-2098-5.0.0-BETA-1808.
AE2: rv4-nightly.
fml-client-latest.log: http://pastebin.com/GMD2MtrB

**Comment by gabizou** [comment]
@mrAppleXZ I've submitted a PR making the necessary change for AE2 and SpongeForge to coexist without crashing at launch, whether there's other bugs that SF indirectly causes with entities/tileentities/items/blocks/etc. is a different story ;) This should be closed as soon as the AE2 issue is resolved.

**Comment by mrapplexz** [comment]
@gabizou Thank you!

**Comment by Orcinuss** [comment]
Are there any updates regarding this issue? From what it looks like from the applied energetic issue is that they are unwilling to fix it, although i'm not entirely sure.

**Comment by bookerthegeek** [comment]
Not unwilling to fix, unwilling to bandaid.

**Comment by mrapplexz** [comment]
Still crashes, but now I have this log:
http://pastebin.com/i3Ww2Vhy - fml-server-latest.log
AE version: rv4-alpha-6.
SpongeForge version: 1.10.2-2123-6.0.0-BETA-1890
MC version: 1.10.2
Forge version: 1.10.2-12.18.2.2151

**Comment by lucasdidur** [comment]
AE: rv4-alpha-7
Sponge: spongeforge-1.10.2-2123-5.1.0-BETA-1911
Forge: 1.10.2-12.18.2.2151

http://pastebin.com/X6svQTbP

**Comment by bloodmc** [comment]
We have reached out to AE2 dev with required PR fix. Once AE2 is stable enough, it will be accepted. For now, there are patched builds out there that should work. Check the AE2 ticket for details.

**Comment by cj89898** [comment]
How can I update myself on if this is released/accepted?

**Comment by JJRockie** [comment]
MY server will not start please help. JJRockie
[02:11:54] [main/DEBUG] [FML/]: Injecting tracing printstreams for STDOUT/STDERR.
[02:11:54] [main/INFO] [FML/]: Forge Mod Loader version 12.18.3.2511 for Minecraft 1.10.2 loading
[02:11:54] [main/INFO] [FML/]: Java is OpenJDK 64-Bit Server VM, version 1.8.0_151, running on Linux:amd64:4.4.0-45-generic, installed at /usr/lib/jvm/java-8-openjdk-amd64/jre
[02:11:54] [main/DEBUG] [FML/]: Java classpath at launch is forge-12.18.3.2511.jar
[02:11:54] [main/DEBUG] [FML/]: Java library path at launch is /usr/java/packages/lib/amd64:/usr/lib/x86_64-linux-gnu/jni:/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/usr/lib/jni:/lib:/usr/lib
[02:11:54] [main/DEBUG] [FML/]: Enabling runtime deobfuscation
[02:11:54] [main/DEBUG] [FML/]: Instantiating coremod class FMLCorePlugin
[02:11:54] [main/DEBUG] [FML/]: Added access transformer class net.minecraftforge.fml.common.asm.transformers.AccessTransformer to enqueued access transformers
[02:11:54] [main/DEBUG] [FML/]: Enqueued coremod FMLCorePlugin
[02:11:54] [main/DEBUG] [FML/]: Instantiating coremod class FMLForgePlugin
[02:11:54] [main/DEBUG] [FML/]: Enqueued coremod FMLForgePlugin
[02:11:54] [main/DEBUG] [FML/]: All fundamental core mods are successfully located
[02:11:54] [main/DEBUG] [FML/]: Attempting to load commandline specified mods, relative to /home/container/.
[02:11:54] [main/DEBUG] [FML/]: Discovering coremods
[02:11:54] [main/DEBUG] [FML/]: Examining for coremod candidacy [1.9.4]Mo'+Villages-1.5.2.jar
[02:11:54] [main/DEBUG] [FML/]: Not found coremod data in [1.9.4]Mo'+Villages-1.5.2.jar
[02:11:54] [main/DEBUG] [FML/]: Examining for coremod candidacy ae2stuff-0.6.0.9-mc1.10.2.jar
[02:11:54] [main/DEBUG] [FML/]: Not found coremod data in ae2stuff-0.6.0.9-mc1.10.2.jar
[02:11:54] [main/DEBUG] [FML/]: Examining for coremod candidacy AnimalBikes_1.10.2(19nov16).jar
[02:11:54] [main/DEBUG] [FML/]: Not found coremod data in AnimalBikes_1.10.2(19nov16).jar
[02:11:54] [main/DEBUG] [FML/]: Examining for coremod candidacy animania-1.10.2-1.4.6.jar
[02:11:54] [main/DEBUG] [FML/]: Not found coremod data in animania-1.10.2-1.4.6.jar
[02:11:54] [main/DEBUG] [FML/]: Examining for coremod candidacy appliedenergistics2-rv4-alpha-11.jar
[02:11:54] [main/TRACE] [FML/]: Found FMLCorePluginContainsFMLMod marker in appliedenergistics2-rv4-alpha-11.jar, it will be examined later for regular @Mod instances
[02:11:54] [main/DEBUG] [FML/]: Instantiating coremod class AppEngCore
[02:11:54] [main/DEBUG] [FML/]: The coremod appeng.coremod.AppEngCore requested minecraft version 1.10.2 and minecraft is 1.10.2. It will be loaded.
[02:11:54] [main/INFO] [FML/]: [AppEng] Core Init
[02:11:54] [main/DEBUG] [FML/]: Enqueued coremod AppEngCore
[02:11:54] [main/DEBUG] [FML/]: Examining for coremod candidacy Aroma1997Core-1.9.4-1.1.1.2.jar
[02:11:54] [main/TRACE] [FML/]: Found FMLCorePluginContainsFMLMod marker in Aroma1997Core-1.9.4-1.1.1.2.jar, it will be examined later for regular @Mod instances
[02:11:54] [main/DEBUG] [FML/]: Instantiating coremod class CoreMod
[02:11:54] [main/WARN] [FML/]: The coremod aroma1997.core.coremod.CoreMod does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[02:11:54] [main/DEBUG] [FML/]: Enqueued coremod CoreMod
[02:11:54] [main/DEBUG] [FML/]: Examining for coremod candidacy Aroma1997s-Dimensional-World-1.9.4-1.2.0.7.jar
[02:11:54] [main/DEBUG] [FML/]: Not found coremod data in Aroma1997s-Dimensional-World-1.9.4-1.2.0.7.jar
[02:11:54] [main/DEBUG] [FML/]: Examining for coremod candidacy ArsMagica2-1.10.2-1.5.0-17.jar
[02:11:54] [main/TRACE] [FML/]: Found FMLCorePluginContainsFMLMod marker in ArsMagica2-1.10.2-1.5.0-17.jar, it will be examined later for regular @Mod instances
[02:11:54] [main/DEBUG] [FML/]: Instantiating coremod class Preloader
[02:11:54] [main/TRACE] [FML/]: coremod named ArsMagica2-Preloader is loading
[02:11:54] [main/WARN] [FML/]: The coremod am2.asm.Preloader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[02:11:54] [main/DEBUG] [FML/]: Enqueued coremod ArsMagica2-Preloader
[02:11:54] [main/DEBUG] [FML/]: Examining for coremod candidacy astralsorcery-1.4.5.jar
[02:11:54] [main/TRACE] [FML/]: Found FMLCorePluginContainsFMLMod marker in astralsorcery-1.4.5.jar, it will be examined later for regular @Mod instances
[02:11:54] [main/DEBUG] [FML/]: Instantiating coremod class AstralCore
[02:11:54] [main/TRACE] [FML/]: coremod named AstralCore is loading
[02:11:54] [main/DEBUG] [FML/]: The coremod hellfirepvp.astralsorcery.core.AstralCore requested minecraft version 1.10.2 and minecraft is 1.10.2. It will be loaded.
[02:11:54] [main/INFO] [FML/]: [AstralCore] Initialized.
[02:11:54] [main/DEBUG] [FML/]: Added access transformer class hellfirepvp.astralsorcery.core.AstralTransformer to enqueued access transformers
[02:11:54] [main/DEBUG] [FML/]: Enqueued coremod AstralCore
[02:11:54] [main/DEBUG] [FML/]: Examining for coremod candidacy Baubles-1.10.2-1.3.13.jar
[02:11:54] [main/DEBUG] [FML/]: Not found coremod data in Baubles-1.10.2-1.3.13.jar
[02:11:54] [main/DEBUG] [FML/]: Examining for coremod candidacy bdlib-1.12.4.25-mc1.10.2.jar
[02:11:54] [main/DEBUG] [FML/]: Not found coremod data in bdlib-1.12.4.25-mc1.10.2.jar
[02:11:54] [main/DEBUG] [FML/]: Examining for coremod candidacy BetterBuildersWands-1.10.2-0.11.1.220+f8232fe.jar
[02:11:54] [main/DEBUG] [FML/]: Not found coremod data in BetterBuildersWands-1.10.2-0.11.1.220+f8232fe.jar
[02:11:54] [main/DEBUG] [FML/]: Examining for coremod candidacy BetterFoliage-MC1.10.2-2.1.11.jar
[02:11:54] [main/TRACE] [FML/]: Found FMLCorePluginContainsFMLMod marker in BetterFoliage-MC1.10.2-2.1.11.jar, it will be examined later for regular @Mod instances
[02:11:54] [main/DEBUG] [FML/]: Instantiating coremod class BetterFoliageLoader
[02:11:54] [main/DEBUG] [FML/]: The coremod mods.betterfoliage.loader.BetterFoliageLoader requested minecraft version 1.10.2 and minecraft is 1.10.2. It will be loaded.
[02:11:54] [main/DEBUG] [FML/]: Enqueued coremod BetterFoliageLoader
[02:11:54] [main/DEBUG] [FML/]: Examining for coremod candidacy BetterFps-1.4.5-1.10.jar
[02:11:54] [main/INFO] [FML/]: Loading tweaker guichaguri.betterfps.tweaker.BetterFpsTweaker from BetterFps-1.4.5-1.10.jar
[02:11:54] [main/DEBUG] [FML/]: Examining for coremod candidacy BiblioCraft[v2.2.5][MC1.10.2].jar
[02:11:54] [main/DEBUG] [FML/]: Not found coremod data in BiblioCraft[v2.2.5][MC1.10.2].jar
[02:11:54] [main/DEBUG] [FML/]: Examining for coremod candidacy BigDoors-1.10.2-1.3.0.jar
[02:11:54] [main/DEBUG] [FML/]: Not found coremod data in BigDoors-1.10.2-1.3.0.jar
[02:11:54] [main/DEBUG] [FML/]: Examining for coremod candidacy BloodMagic-1.10.2.jar
[02:11:54] [main/DEBUG] [FML/]: Not found coremod data in BloodMagic-1.10.2.jar
[02:11:54] [main/DEBUG] [FML/]: Examining for coremod candidacy Bookshelf-1.10.2-1.4.1.320.jar
[02:11:54] [main/TRACE] [FML/]: Found FMLCorePluginContainsFMLMod marker in Bookshelf-1.10.2-1.4.1.320.jar, it will be examined later for regular @Mod instances
[02:11:54] [main/DEBUG] [FML/]: Instantiating coremod class BookshelfLoadingPlugin
[02:11:54] [main/DEBUG] [FML/]: The coremod net.darkhax.bookshelf.asm.BookshelfLoadingPlugin requested minecraft version 1.10.2 and minecraft is 1.10.2. It will be loaded.
[02:11:54] [main/DEBUG] [FML/]: Enqueued coremod BookshelfLoadingPlugin
[02:11:54] [main/DEBUG] [FML/]: Examining for coremod candidacy BrandonsCore-1.10.2-2.1.14.137-universal.jar
[02:11:54] [main/TRACE] [FML/]: Found FMLCorePluginContainsFMLMod marker in BrandonsCore-1.10.2-2.1.14.137-universal.jar, it will be examined later for regular @Mod instances
[02:11:54] [main/DEBUG] [FML/]: Instantiating coremod class LoadingPlugin
[02:11:54] [main/TRACE] [FML/]: coremod named Brandon's Core is loading
[02:11:54] [main/DEBUG] [FML/]: The coremod com.brandon3055.brandonscore.asm.LoadingPlugin requested minecraft version 1.10.2 and minecraft is 1.10.2. It will be loaded.
[02:11:54] [main/DEBUG] [FML/]: Enqueued coremod Brandon's Core
[02:11:54] [main/DEBUG] [FML/]: Examining for coremod candidacy BuildingBricks-1.10.2-2.0.13.jar
[02:11:54] [main/TRACE] [FML/]: Found FMLCorePluginContainsFMLMod marker in BuildingBricks-1.10.2-2.0.13.jar, it will be examined later for regular @Mod instances
[02:11:54] [main/DEBUG] [FML/]: Instantiating coremod class LoadingPluginBuildingBricks
[02:11:55] [main/INFO] [H3NTBootstrap.Bootstrap/]: initializing
[02:11:55] [main/DEBUG] [H3NTBootstrap.Bootstrap/]: mod buildingbricks provides h3nt-mappings version 1.1.1 and requires version 1.1.1
[02:11:55] [main/DEBUG] [H3NTBootstrap.Bootstrap/]: mod buildingbricks provides h3nt-asmtweaks version 1.1.1 and requires version 1.1.1
[02:11:55] [main/DEBUG] [H3NTBootstrap.Bootstrap/]: mod buildingbricks provides h3nt-commonutils version 1.9.4-2.2.2 and requires version 1.9.4-2.2.x
[02:11:55] [main/ERROR] [H3NTBootstrap.Bootstrap/]: Could not open the jar file
java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method) ~[?:1.8.0_151]
	at java.util.zip.ZipFile.<init>(ZipFile.java:225) ~[?:1.8.0_151]
	at java.util.zip.ZipFile.<init>(ZipFile.java:155) ~[?:1.8.0_151]
	at java.util.zip.ZipFile.<init>(ZipFile.java:169) ~[?:1.8.0_151]
	at com.hea3ven.tools.bootstrap.Bootstrap.discoverFromZip(Bootstrap.java:124) [Bootstrap.class:?]
	at com.hea3ven.tools.bootstrap.Bootstrap.discoverFromDir(Bootstrap.java:115) [Bootstrap.class:?]
	at com.hea3ven.tools.bootstrap.Bootstrap.discover(Bootstrap.java:104) [Bootstrap.class:?]
	at com.hea3ven.tools.bootstrap.Bootstrap.init(Bootstrap.java:61) [Bootstrap.class:?]
	at com.hea3ven.buildingbricks.core.load.LoadingPluginBuildingBricks.<clinit>(LoadingPluginBuildingBricks.java:11) [BuildingBricks-1.10.2-2.0.13.jar:?]
	at java.lang.Class.forName0(Native Method) [?:1.8.0_151]
	at java.lang.Class.forName(Class.java:348) [?:1.8.0_151]
	at net.minecraftforge.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:564) [forge-12.18.3.2511.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:425) [forge-12.18.3.2511.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:255) [forge-12.18.3.2511.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:102) [forge-12.18.3.2511.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupServer(FMLLaunchHandler.java:86) [forge-12.18.3.2511.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.configureForServerLaunch(FMLLaunchHandler.java:46) [forge-12.18.3.2511.jar:?]
	at net.minecraftforge.fml.common.launcher.FMLServerTweaker.injectIntoClassLoader(FMLServerTweaker.java:62) [forge-12.18.3.2511.jar:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_151]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_151]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_151]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_151]
	at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:62) [forge-12.18.3.2511.jar:?]
	at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:31) [forge-12.18.3.2511.jar:?]
[02:11:55] [main/INFO] [H3NTBootstrap.Bootstrap/]: loading libraries
[02:11:55] [main/DEBUG] [H3NTBootstrap.Bootstrap/]: extracting libraries to /home/container/mods/h3ntlibs
[02:11:55] [main/DEBUG] [H3NTBootstrap.Bootstrap/]: loading library h3nt-commonutils-1.9.4-2.2.2.jar
[02:11:55] [main/DEBUG] [H3NTBootstrap.Bootstrap/]: adding file:/home/container/mods/h3ntlibs/h3nt-commonutils-1.9.4-2.2.2.jar to classpath
[02:11:55] [main/DEBUG] [H3NTBootstrap.Bootstrap/]: loading library h3nt-mappings-1.1.1.jar
[02:11:55] [main/DEBUG] [H3NTBootstrap.Bootstrap/]: adding file:/home/container/mods/h3ntlibs/h3nt-mappings-1.1.1.jar to classpath
[02:11:55] [main/DEBUG] [H3NTBootstrap.Bootstrap/]: loading library h3nt-asmtweaks-1.1.1.jar
[02:11:55] [main/DEBUG] [H3NTBootstrap.Bootstrap/]: adding file:/home/container/mods/h3ntlibs/h3nt-asmtweaks-1.1.1.jar to classpath
[02:11:55] [main/WARN] [FML/]: The coremod com.hea3ven.buildingbricks.core.load.LoadingPluginBuildingBricks does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[02:11:55] [main/DEBUG] [FML/]: Enqueued coremod LoadingPluginBuildingBricks
[02:11:55] [main/DEBUG] [FML/]: Examining for coremod candidacy CatClearLag-0.8.jar
[02:11:55] [main/DEBUG] [FML/]: Not found coremod data in CatClearLag-0.8.jar
[02:11:55] [main/DEBUG] [FML/]: Examining for coremod candidacy chickens-4.3.2.jar
[02:11:55] [main/DEBUG] [FML/]: Not found coremod data in chickens-4.3.2.jar
[02:11:55] [main/DEBUG] [FML/]: Examining for coremod candidacy CodeChickenCore-1.10.2-Recommended.jar
[02:11:55] [main/DEBUG] [FML/]: Not found coremod data in CodeChickenCore-1.10.2-Recommended.jar
[02:11:55] [main/DEBUG] [FML/]: Examining for coremod candidacy CodeChickenLib-1.10.2-2.5.9.320-universal.jar
[02:11:55] [main/TRACE] [FML/]: Found FMLCorePluginContainsFMLMod marker in CodeChickenLib-1.10.2-2.5.9.320-universal.jar, it will be examined later for regular @Mod instances
[02:11:55] [main/DEBUG] [FML/]: Instantiating coremod class CCLCorePlugin
[02:11:55] [main/WARN] [FML/]: The coremod codechicken.lib.asm.CCLCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[02:11:55] [main/DEBUG] [FML/]: Enqueued coremod CCLCorePlugin
[02:11:55] [main/DEBUG] [FML/]: Examining for coremod candidacy CoFHCore-1.10.2.jar
[02:11:55] [main/TRACE] [FML/]: Found FMLCorePluginContainsFMLMod marker in CoFHCore-1.10.2.jar, it will be examined later for regular @Mod instances
[02:11:56] [main/DEBUG] [FML/]: Instantiating coremod class LoadingPlugin
[02:11:56] [main/TRACE] [FML/]: coremod named CoFH Loading Plugin is loading
[02:11:56] [main/WARN] [FML/]: The coremod cofh.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[02:11:56] [main/DEBUG] [FML/]: Added access transformer class cofh.asm.CoFHAccessTransformer to enqueued access transformers
[02:11:56] [main/DEBUG] [FML/]: Enqueued coremod CoFH Loading Plugin
[02:11:56] [main/DEBUG] [FML/]: Examining for coremod candidacy CommandKits-v1.2.0.jar
[02:11:56] [main/DEBUG] [FML/]: Not found coremod data in CommandKits-v1.2.0.jar
[02:11:56] [main/DEBUG] [FML/]: Examining for coremod candidacy coroutil-1.10.2-1.1.18.jar
[02:11:56] [main/DEBUG] [FML/]: Not found coremod data in coroutil-1.10.2-1.1.18.jar
[02:11:56] [main/DEBUG] [FML/]: Examining for coremod candidacy CraftStudioAPI-universal-0.3.0.87-mc1.10.2-beta (1).jar
[02:11:56] [main/DEBUG] [FML/]: Not found coremod data in CraftStudioAPI-universal-0.3.0.87-mc1.10.2-beta (1).jar
[02:11:56] [main/DEBUG] [FML/]: Examining for coremod candidacy CreativeCore+v1.7.3+mc1.10.2.jar
[02:11:56] [main/TRACE] [FML/]: Found FMLCorePluginContainsFMLMod marker in CreativeCore+v1.7.3+mc1.10.2.jar, it will be examined later for regular @Mod instances
[02:11:56] [main/DEBUG] [FML/]: Instantiating coremod class CreativePatchingLoader
[02:11:56] [main/WARN] [FML/]: The coremod com.creativemd.creativecore.core.CreativePatchingLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[02:11:56] [main/DEBUG] [FML/]: Enqueued coremod CreativePatchingLoader
[02:11:56] [main/DEBUG] [FML/]: Examining for coremod candidacy CustomMainMenu-MC1.10.2-2.0.5.jar
[02:11:56] [main/DEBUG] [FML/]: Not found coremod data in CustomMainMenu-MC1.10.2-2.0.5.jar
[02:11:56] [main/DEBUG] [FML/]: Examining for coremod candidacy CustomNPCs.jar
[02:11:56] [main/DEBUG] [FML/]: Not found coremod data in CustomNPCs.jar
[02:11:56] [main/DEBUG] [FML/]: Examining for coremod candidacy DailyRewards-api5-6-1.2.2.jar
[02:11:56] [main/DEBUG] [FML/]: Not found coremod data in DailyRewards-api5-6-1.2.2.jar
[02:11:56] [main/DEBUG] [FML/]: Examining for coremod candidacy Draconic-Evolution-1.10.2-2.1.8.273-universal.jar
[02:11:56] [main/DEBUG] [FML/]: Not found coremod data in Draconic-Evolution-1.10.2-2.1.8.273-universal.jar
[02:11:56] [main/DEBUG] [FML/]: Examining for coremod candidacy Dragon-Mounts-Mod-1.10.2.jar
[02:11:56] [main/DEBUG] [FML/]: Not found coremod data in Dragon-Mounts-Mod-1.10.2.jar
[02:11:56] [main/DEBUG] [FML/]: Examining for coremod candidacy DragonRealm_v2.0.1_1.10.2.jar
[02:11:56] [main/DEBUG] [FML/]: Not found coremod data in DragonRealm_v2.0.1_1.10.2.jar
[02:11:56] [main/DEBUG] [FML/]: Examining for coremod candidacy DrZhark's+Mo'Creatures+Mod-10.0.6.jar
[02:11:56] [main/DEBUG] [FML/]: Not found coremod data in DrZhark's+Mo'Creatures+Mod-10.0.6.jar
[02:11:56] [main/DEBUG] [FML/]: Examining for coremod candidacy DynamicSurroundings-1.10.2-3.4.9.6.jar
[02:11:56] [main/TRACE] [FML/]: Found FMLCorePluginContainsFMLMod marker in DynamicSurroundings-1.10.2-3.4.9.6.jar, it will be examined later for regular @Mod instances
[02:11:56] [main/DEBUG] [FML/]: Instantiating coremod class TransformLoader
[02:11:56] [main/TRACE] [FML/]: coremod named DynamicSurroundingsCore is loading
[02:11:56] [main/WARN] [FML/]: The coremod org.blockartistry.DynSurround.asm.TransformLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[02:11:56] [main/DEBUG] [FML/]: Enqueued coremod DynamicSurroundingsCore
[02:11:56] [main/DEBUG] [FML/]: Examining for coremod candidacy easykits-7.1.0-0.2.1.jar
[02:11:56] [main/DEBUG] [FML/]: Not found coremod data in easykits-7.1.0-0.2.1.jar
[02:11:56] [main/DEBUG] [FML/]: Examining for coremod candidacy ElecCore-1.10.2-1.7.431.jar
[02:11:56] [main/DEBUG] [FML/]: Not found coremod data in ElecCore-1.10.2-1.7.431.jar
[02:11:56] [main/DEBUG] [FML/]: Examining for coremod candidacy ElevatorMod[V.1.3.0][MC.1.10.2].jar
[02:11:56] [main/DEBUG] [FML/]: Not found coremod data in ElevatorMod[V.1.3.0][MC.1.10.2].jar
[02:11:56] [main/DEBUG] [FML/]: Examining for coremod candidacy Enchanting-Plus-Mod-1.10.2.jar
[02:11:56] [main/DEBUG] [FML/]: Not found coremod data in Enchanting-Plus-Mod-1.10.2.jar
[02:11:56] [main/DEBUG] [FML/]: Examining for coremod candidacy EnchantmentLeveler.jar
[02:11:56] [main/DEBUG] [FML/]: Not found coremod data in EnchantmentLeveler.jar
[02:11:56] [main/DEBUG] [FML/]: Examining for coremod candidacy EnderCore-1.10.2.jar
[02:11:56] [main/TRACE] [FML/]: Found FMLCorePluginContainsFMLMod marker in EnderCore-1.10.2.jar, it will be examined later for regular @Mod instances
[02:11:56] [main/DEBUG] [FML/]: Instantiating coremod class EnderCorePlugin
[02:11:56] [main/DEBUG] [FML/]: The coremod com.enderio.core.common.transform.EnderCorePlugin requested minecraft version 1.10.2 and minecraft is 1.10.2. It will be loaded.
[02:11:56] [main/DEBUG] [FML/]: Enqueued coremod EnderCorePlugin
[02:11:56] [main/DEBUG] [FML/]: Examining for coremod candidacy EnderIO-1.10.2-3.1.193.jar
[02:11:56] [main/DEBUG] [FML/]: Not found coremod data in EnderIO-1.10.2-3.1.193.jar
[02:11:56] [main/DEBUG] [FML/]: Examining for coremod candidacy EnderZoo-1.10-1.2.3.44.jar
[02:11:56] [main/DEBUG] [FML/]: Not found coremod data in EnderZoo-1.10-1.2.3.44.jar
[02:11:56] [main/DEBUG] [FML/]: Examining for coremod candidacy Exotic+Birds+1.10.2-1.4.2.jar
[02:11:56] [main/DEBUG] [FML/]: Not found coremod data in Exotic+Birds+1.10.2-1.4.2.jar
[02:11:56] [main/DEBUG] [FML/]: Examining for coremod candidacy ExtraPlanets-1.10.2.jar
[02:11:56] [main/DEBUG] [FML/]: Not found coremod data in ExtraPlanets-1.10.2.jar
[02:11:56] [main/DEBUG] [FML/]: Examining for coremod candidacy extrautils2-1.10.2-1.7.4.jar
[02:11:56] [main/DEBUG] [FML/]: Not found coremod data in extrautils2-1.10.2-1.7.4.jar
[02:11:56] [main/DEBUG] [FML/]: Examining for coremod candidacy ExtremeReactors-1.10.2-0.4.5.46.jar
[02:11:56] [main/DEBUG] [FML/]: Not found coremod data in ExtremeReactors-1.10.2-0.4.5.46.jar
[02:11:56] [main/DEBUG] [FML/]: Examining for coremod candidacy FastLeafDecay-v11.jar
[02:11:56] [main/DEBUG] [FML/]: Not found coremod data in FastLeafDecay-v11.jar
[02:11:56] [main/DEBUG] [FML/]: Examining for coremod candidacy Flowercraftmod+v6.01+-+MC1.10.2+Forge.jar
[02:11:56] [main/DEBUG] [FML/]: Not found coremod data in Flowercraftmod+v6.01+-+MC1.10.2+Forge.jar
[02:11:56] [main/DEBUG] [FML/]: Examining for coremod candidacy forestry_1.10.2-5.2.17.389.jar
[02:11:56] [main/DEBUG] [FML/]: Not found coremod data in forestry_1.10.2-5.2.17.389.jar
[02:11:56] [main/DEBUG] [FML/]: Examining for coremod candidacy Galacticraft-Planets-1.10.2-4.0.1.136.jar
[02:11:56] [main/DEBUG] [FML/]: Not found coremod data in Galacticraft-Planets-1.10.2-4.0.1.136.jar
[02:11:56] [main/DEBUG] [FML/]: Examining for coremod candidacy GalacticraftCore-1.10.2-4.0.1.136.jar
[02:11:56] [main/DEBUG] [FML/]: Not found coremod data in GalacticraftCore-1.10.2-4.0.1.136.jar
[02:11:56] [main/DEBUG] [FML/]: Examining for coremod candidacy gendustry-1.6.5.26-mc1.10.2.jar
[02:11:56] [main/DEBUG] [FML/]: Not found coremod data in gendustry-1.6.5.26-mc1.10.2.jar
[02:11:56] [main/DEBUG] [FML/]: Examining for coremod candidacy gravestone-1.5.13.jar
[02:11:56] [main/DEBUG] [FML/]: Not found coremod data in gravestone-1.5.13.jar
[02:11:56] [main/DEBUG] [FML/]: Examining for coremod candidacy griefprevention-1.10.2-4.0.1.558-original.jar
[02:11:56] [main/DEBUG] [FML/]: Not found coremod data in griefprevention-1.10.2-4.0.1.558-original.jar
[02:11:56] [main/DEBUG] [FML/]: Examining for coremod candidacy Grue-1.9.4-1.3.5.jar
[02:11:56] [main/DEBUG] [FML/]: Not found coremod data in Grue-1.9.4-1.3.5.jar
[02:11:56] [main/DEBUG] [FML/]: Examining for coremod candidacy Guide-API-1.10.2-2.0.3-46.jar
[02:11:56] [main/DEBUG] [FML/]: Not found coremod data in Guide-API-1.10.2-2.0.3-46.jar
[02:11:56] [main/DEBUG] [FML/]: Examining for coremod candidacy HomeSetHome1-0.jar
[02:11:56] [main/DEBUG] [FML/]: Not found coremod data in HomeSetHome1-0.jar
[02:11:56] [main/DEBUG] [FML/]: Examining for coremod candidacy iceandfire-1.0.1.jar
[02:11:56] [main/TRACE] [FML/]: Found FMLCorePluginContainsFMLMod marker in iceandfire-1.0.1.jar, it will be examined later for regular @Mod instances
[02:11:56] [main/DEBUG] [FML/]: Instantiating coremod class IceAndFireForgeLoading
[02:11:56] [main/DEBUG] [FML/]: The coremod com.github.alexthe666.iceandfire.access.IceAndFireForgeLoading requested minecraft version 1.10.2 and minecraft is 1.10.2. It will be loaded.
[02:11:56] [main/DEBUG] [FML/]: Enqueued coremod IceAndFireForgeLoading
[02:11:56] [main/DEBUG] [FML/]: Examining for coremod candidacy industrialcraft-2-2.6.252-ex110.jar
[02:11:56] [main/TRACE] [FML/]: Found FMLCorePluginContainsFMLMod marker in industrialcraft-2-2.6.252-ex110.jar, it will be examined later for regular @Mod instances
[02:11:56] [main/DEBUG] [FML/]: Instantiating coremod class IC2core
[02:11:56] [main/WARN] [FML/]: The coremod ic2.core.coremod.IC2core does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[02:11:56] [main/DEBUG] [FML/]: Enqueued coremod IC2core
[02:11:56] [main/DEBUG] [FML/]: Examining for coremod candidacy inventorypets-1.10-1.4.9.9b.jar
[02:11:56] [main/DEBUG] [FML/]: Not found coremod data in inventorypets-1.10-1.4.9.9b.jar
[02:11:56] [main/DEBUG] [FML/]: Examining for coremod candidacy ironchest-1.10.2-7.0.15.804.jar
[02:11:56] [main/DEBUG] [FML/]: Not found coremod data in ironchest-1.10.2-7.0.15.804.jar
[02:11:56] [main/DEBUG] [FML/]: Examining for coremod candidacy itorch-1.10.2-0.1.5.jar
[02:11:56] [main/DEBUG] [FML/]: Not found coremod data in itorch-1.10.2-0.1.5.jar
[02:11:56] [main/DEBUG] [FML/]: Examining for coremod candidacy jei_1.10.2-3.14.7.416.jar
[02:11:56] [main/DEBUG] [FML/]: Not found coremod data in jei_1.10.2-3.14.7.416.jar
[02:11:56] [main/DEBUG] [FML/]: Examining for coremod candidacy journeymap-1.10.2-5.5.2.jar
[02:11:56] [main/DEBUG] [FML/]: Not found coremod data in journeymap-1.10.2-5.5.2.jar
[02:11:56] [main/DEBUG] [FML/]: Examining for coremod candidacy JurassiCraft-2.1.3-Fix.jar
[02:11:56] [main/DEBUG] [FML/]: Not found coremod data in JurassiCraft-2.1.3-Fix.jar
[02:11:56] [main/DEBUG] [FML/]: Examining for coremod candidacy JustEnoughResources-1.10.2-0.5.8.98.jar
[02:11:56] [main/DEBUG] [FML/]: Not found coremod data in JustEnoughResources-1.10.2-0.5.8.98.jar
[02:11:56] [main/DEBUG] [FML/]: Examining for coremod candidacy llibrary-1.7.7-1.10.2.jar
[02:11:56] [main/TRACE] [FML/]: Found FMLCorePluginContainsFMLMod marker in llibrary-1.7.7-1.10.2.jar, it will be examined later for regular @Mod instances
[02:11:56] [main/DEBUG] [FML/]: Instantiating coremod class LLibraryPlugin
[02:11:56] [main/TRACE] [FML/]: coremod named llibrary is loading
[02:11:56] [main/DEBUG] [FML/]: The coremod net.ilexiconn.llibrary.server.core.plugin.LLibraryPlugin requested minecraft version 1.10.2 and minecraft is 1.10.2. It will be loaded.
[02:11:56] [main/DEBUG] [FML/]: Enqueued coremod llibrary
[02:11:56] [main/DEBUG] [FML/]: Examining for coremod candidacy LunatriusCore-1.10.2-1.1.2.36-universal.jar
[02:11:56] [main/DEBUG] [FML/]: Not found coremod data in LunatriusCore-1.10.2-1.1.2.36-universal.jar
[02:11:56] [main/DEBUG] [FML/]: Examining for coremod candidacy LycanitesMobsComplete+1.17.1.2+[1.10.2].jar
[02:11:56] [main/DEBUG] [FML/]: Not found coremod data in LycanitesMobsComplete+1.17.1.2+[1.10.2].jar
[02:11:56] [main/DEBUG] [FML/]: Examining for coremod candidacy MagicBees-Alpha-3.0.2.jar
[02:11:56] [main/DEBUG] [FML/]: Not found coremod data in MagicBees-Alpha-3.0.2.jar
[02:11:56] [main/DEBUG] [FML/]: Examining for coremod candidacy malisiscore-1.10.2-4.4.0.jar
[02:11:56] [main/TRACE] [FML/]: Found FMLCorePluginContainsFMLMod marker in malisiscore-1.10.2-4.4.0.jar, it will be examined later for regular @Mod instances
[02:11:56] [main/DEBUG] [FML/]: Instantiating coremod class MalisisCorePlugin
[02:11:56] [main/WARN] [FML/]: The coremod net.malisis.core.asm.MalisisCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[02:11:56] [main/DEBUG] [FML/]: Enqueued coremod MalisisCorePlugin
[02:11:56] [main/DEBUG] [FML/]: Examining for coremod candidacy malisisdoors-1.10.2-5.2.0.jar
[02:11:56] [main/DEBUG] [FML/]: Not found coremod data in malisisdoors-1.10.2-5.2.0.jar
[02:11:56] [main/DEBUG] [FML/]: Examining for coremod candidacy Mantle-1.10.2-1.1.5.jar
[02:11:56] [main/DEBUG] [FML/]: Not found coremod data in Mantle-1.10.2-1.1.5.jar
[02:11:56] [main/DEBUG] [FML/]: Examining for coremod candidacy MCMultiPart-1.4.0-universal.jar
[02:11:56] [main/DEBUG] [FML/]: Not found coremod data in MCMultiPart-1.4.0-universal.jar
[02:11:56] [main/DEBUG] [FML/]: Examining for coremod candidacy Mekanism-1.10.2-9.2.4.103.jar
[02:11:56] [main/DEBUG] [FML/]: Not found coremod data in Mekanism-1.10.2-9.2.4.103.jar
[02:11:56] [main/DEBUG] [FML/]: Examining for coremod candidacy metamorph-1.1.4-1.10.2.jar
[02:11:56] [main/DEBUG] [FML/]: Not found coremod data in metamorph-1.1.4-1.10.2.jar
[02:11:56] [main/DEBUG] [FML/]: Examining for coremod candidacy MicdoodleCore-1.10.2-4.0.1.136.jar
[02:11:56] [main/TRACE] [FML/]: Adding MicdoodleCore-1.10.2-4.0.1.136.jar to the list of known coremods, it will not be examined again
[02:11:56] [main/DEBUG] [FML/]: Instantiating coremod class MicdoodlePlugin
[02:11:56] [main/WARN] [FML/]: The coremod micdoodle8.mods.miccore.MicdoodlePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[02:11:56] [main/DEBUG] [FML/]: Added access transformer class micdoodle8.mods.miccore.MicdoodleAccessTransformer to enqueued access transformers
[02:11:56] [main/DEBUG] [FML/]: Enqueued coremod MicdoodlePlugin
[02:11:56] [main/DEBUG] [FML/]: Examining for coremod candidacy minecolonies-universal-1.10.2-0.9.7525.jar
[02:11:56] [main/DEBUG] [FML/]: Not found coremod data in minecolonies-universal-1.10.2-0.9.7525.jar
[02:11:56] [main/DEBUG] [FML/]: Examining for coremod candidacy Minenautica+v1.2.0.jar
[02:11:56] [main/DEBUG] [FML/]: Not found coremod data in Minenautica+v1.2.0.jar
[02:11:56] [main/DEBUG] [FML/]: Examining for coremod candidacy MineReset-1.0.8.BETA2.jar
[02:11:56] [main/DEBUG] [FML/]: Not found coremod data in MineReset-1.0.8.BETA2.jar
[02:11:56] [main/DEBUG] [FML/]: Examining for coremod candidacy MJRLegendsLib-1.10.2-1.0.4.jar
[02:11:56] [main/DEBUG] [FML/]: Not found coremod data in MJRLegendsLib-1.10.2-1.0.4.jar
[02:11:56] [main/DEBUG] [FML/]: Examining for coremod candidacy mobends-0.22.5_for_MC-1.10.2.jar
[02:11:56] [main/DEBUG] [FML/]: Not found coremod data in mobends-0.22.5_for_MC-1.10.2.jar
[02:11:56] [main/DEBUG] [FML/]: Examining for coremod candidacy ModularPowersuits-1.10.2-1.2.129.jar
[02:11:56] [main/DEBUG] [FML/]: Not found coremod data in ModularPowersuits-1.10.2-1.2.129.jar
[02:11:56] [main/DEBUG] [FML/]: Examining for coremod candidacy moreoverlays-1.11-mc1.10.2.jar
[02:11:56] [main/DEBUG] [FML/]: Not found coremod data in moreoverlays-1.11-mc1.10.2.jar
[02:11:56] [main/DEBUG] [FML/]: Examining for coremod candidacy mysticalagriculture-1.10.2-1.5.10.jar
[02:11:56] [main/DEBUG] [FML/]: Not found coremod data in mysticalagriculture-1.10.2-1.5.10.jar
[02:11:56] [main/DEBUG] [FML/]: Examining for coremod candidacy MythicMobs-2.5.1.jar
[02:11:56] [main/DEBUG] [FML/]: Not found coremod data in MythicMobs-2.5.1.jar
[02:11:56] [main/DEBUG] [FML/]: Examining for coremod candidacy NoXray.jar
[02:11:56] [main/INFO] [FML/]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from NoXray.jar
[02:11:56] [main/DEBUG] [FML/]: Examining for coremod candidacy omlib-1.10.2-3.0.0-133.jar
[02:11:56] [main/DEBUG] [FML/]: Not found coremod data in omlib-1.10.2-3.0.0-133.jar
[02:11:56] [main/DEBUG] [FML/]: Examining for coremod candidacy OpenBlocks-1.10.2-1.7.6.jar
[02:11:56] [main/DEBUG] [FML/]: Not found coremod data in OpenBlocks-1.10.2-1.7.6.jar
[02:11:56] [main/DEBUG] [FML/]: Examining for coremod candidacy OpenModsLib-1.10.2-0.11.5.jar
[02:11:56] [main/TRACE] [FML/]: Found FMLCorePluginContainsFMLMod marker in OpenModsLib-1.10.2-0.11.5.jar, it will be examined later for regular @Mod instances
[02:11:56] [main/DEBUG] [FML/]: Instantiating coremod class OpenModsCorePlugin
[02:11:56] [main/WARN] [FML/]: The coremod openmods.core.OpenModsCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[02:11:56] [main/DEBUG] [OpenMods/]: openmods.core.OpenModsCorePlugin.<init>(OpenModsCorePlugin.java:18): <OpenModsLib 0.11.5>\o
[02:11:56] [main/DEBUG] [FML/]: Enqueued coremod OpenModsCorePlugin
[02:11:56] [main/DEBUG] [FML/]: Examining for coremod candidacy openmodularturrets-1.10.2-3.0.0-236.jar
[02:11:56] [main/DEBUG] [FML/]: Not found coremod data in openmodularturrets-1.10.2-3.0.0-236.jar
[02:11:56] [main/DEBUG] [FML/]: Examining for coremod candidacy OptiFine_1.10.2_HD_U_D4.jar
[02:11:56] [main/INFO] [FML/]: Loading tweaker optifine.OptiFineForgeTweaker from OptiFine_1.10.2_HD_U_D4.jar
[02:11:56] [main/DEBUG] [FML/]: Examining for coremod candidacy permissionmanager-3.0.1.jar
[02:11:56] [main/DEBUG] [FML/]: Not found coremod data in permissionmanager-3.0.1.jar
[02:11:56] [main/DEBUG] [FML/]: Examining for coremod candidacy ProgressiveAutomation-1.10.2-1.7.4.jar
[02:11:56] [main/DEBUG] [FML/]: Not found coremod data in ProgressiveAutomation-1.10.2-1.7.4.jar
[02:11:56] [main/DEBUG] [FML/]: Examining for coremod candidacy projectcore-7.0.0-0.2.1.jar
[02:11:56] [main/DEBUG] [FML/]: Not found coremod data in projectcore-7.0.0-0.2.1.jar
[02:11:56] [main/DEBUG] [FML/]: Examining for coremod candidacy ProjectE-1.10.2-PE1.3.1.jar
[02:11:56] [main/DEBUG] [FML/]: Not found coremod data in ProjectE-1.10.2-PE1.3.1.jar
[02:11:56] [main/DEBUG] [FML/]: Examining for coremod candidacy Railcraft_1.10.2-10.3.1.jar
[02:11:56] [main/DEBUG] [FML/]: Not found coremod data in Railcraft_1.10.2-10.3.1.jar
[02:11:56] [main/DEBUG] [FML/]: Examining for coremod candidacy RandomThings-MC1.10.2-3.7.7.1.jar
[02:11:56] [main/TRACE] [FML/]: Found FMLCorePluginContainsFMLMod marker in RandomThings-MC1.10.2-3.7.7.1.jar, it will be examined later for regular @Mod instances
[02:11:56] [main/DEBUG] [FML/]: Instantiating coremod class LoadingPlugin
[02:11:56] [main/WARN] [FML/]: The coremod lumien.randomthings.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[02:11:56] [main/DEBUG] [FML/]: Enqueued coremod LoadingPlugin
[02:11:56] [main/DEBUG] [FML/]: Examining for coremod candidacy reptilemod-1.10.2-3.5.2-58.jar
[02:11:56] [main/DEBUG] [FML/]: Not found coremod data in reptilemod-1.10.2-3.5.2-58.jar
[02:11:56] [main/DEBUG] [FML/]: Examining for coremod candidacy ResourceLoader-MC1.9.4-1.5.1.jar
[02:11:56] [main/TRACE] [FML/]: Found FMLCorePluginContainsFMLMod marker in ResourceLoader-MC1.9.4-1.5.1.jar, it will be examined later for regular @Mod instances
[02:11:56] [main/DEBUG] [FML/]: Instantiating coremod class LoadingPlugin
[02:11:56] [main/WARN] [FML/]: The coremod lumien.resourceloader.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[02:11:56] [main/DEBUG] [FML/]: Enqueued coremod LoadingPlugin
[02:11:56] [main/DEBUG] [FML/]: Examining for coremod candidacy rockhounding_chemistry-1.10.2-1.63.jar
[02:11:56] [main/DEBUG] [FML/]: Not found coremod data in rockhounding_chemistry-1.10.2-1.63.jar
[02:11:56] [main/DEBUG] [FML/]: Examining for coremod candidacy rockhounding_core-1.10.2-1.11.jar
[02:11:56] [main/DEBUG] [FML/]: Not found coremod data in rockhounding_core-1.10.2-1.11.jar
[02:11:56] [main/DEBUG] [FML/]: Examining for coremod candidacy rockhounding_rocks-1.10.2-1.12.jar
[02:11:56] [main/DEBUG] [FML/]: Not found coremod data in rockhounding_rocks-1.10.2-1.12.jar
[02:11:56] [main/DEBUG] [FML/]: Examining for coremod candidacy Schematica-1.10.2-1.7.8.153-universal.jar
[02:11:56] [main/DEBUG] [FML/]: Not found coremod data in Schematica-1.10.2-1.7.8.153-universal.jar
[02:11:56] [main/DEBUG] [FML/]: Examining for coremod candidacy SimpleAchievements-MC1.9.4-1.2.2-28.jar
[02:11:56] [main/DEBUG] [FML/]: Not found coremod data in SimpleAchievements-MC1.9.4-1.2.2-28.jar
[02:11:56] [main/DEBUG] [FML/]: Examining for coremod candidacy SimplyJetpacks2-1.10.2-2.1.3.55.jar
[02:11:56] [main/DEBUG] [FML/]: Not found coremod data in SimplyJetpacks2-1.10.2-2.1.3.55.jar
[02:11:56] [main/DEBUG] [FML/]: Examining for coremod candidacy SoManyEnchantments+V0.2.0+(1.10.2).jar
[02:11:56] [main/DEBUG] [FML/]: Not found coremod data in SoManyEnchantments+V0.2.0+(1.10.2).jar
[02:11:56] [main/DEBUG] [FML/]: Examining for coremod candidacy SonarCore-1.10.2-3.3.0.jar
[02:11:56] [main/DEBUG] [FML/]: Not found coremod data in SonarCore-1.10.2-3.3.0.jar
[02:11:56] [main/DEBUG] [FML/]: Examining for coremod candidacy spongeforge-1.10.2-2477-5.2.0-BETA-2793.jar
[02:11:56] [main/INFO] [FML/]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from spongeforge-1.10.2-2477-5.2.0-BETA-2793.jar
[02:11:56] [main/DEBUG] [FML/]: Examining for coremod candidacy TConstruct-1.10.2-2.6.5.jar
[02:11:56] [main/DEBUG] [FML/]: Not found coremod data in TConstruct-1.10.2-2.6.5.jar
[02:11:56] [main/DEBUG] [FML/]: Examining for coremod candidacy The+Beneath-1.10.2-1.3.0.jar
[02:11:56] [main/DEBUG] [FML/]: Not found coremod data in The+Beneath-1.10.2-1.3.0.jar
[02:11:56] [main/DEBUG] [FML/]: Examining for coremod candidacy Thermal-Smeltery-Mod-1.10.2.jar
[02:11:56] [main/DEBUG] [FML/]: Not found coremod data in Thermal-Smeltery-Mod-1.10.2.jar
[02:11:56] [main/DEBUG] [FML/]: Examining for coremod candidacy ThermalDynamics-1.10.2-2.0.11.19-universal.jar
[02:11:56] [main/DEBUG] [FML/]: Not found coremod data in ThermalDynamics-1.10.2-2.0.11.19-universal.jar
[02:11:56] [main/DEBUG] [FML/]: Examining for coremod candidacy ThermalExpansion-1.10.2-5.1.10.28-universal.jar
[02:11:56] [main/DEBUG] [FML/]: Not found coremod data in ThermalExpansion-1.10.2-5.1.10.28-universal.jar
[02:11:56] [main/DEBUG] [FML/]: Examining for coremod candidacy ThermalFoundation-1.10.2-2.1.5.12-universal.jar
[02:11:56] [main/DEBUG] [FML/]: Not found coremod data in ThermalFoundation-1.10.2-2.1.5.12-universal.jar
[02:11:56] [main/DEBUG] [FML/]: Examining for coremod candidacy tinker_io-1.10.2-release 2.4.4b.jar
[02:11:56] [main/DEBUG] [FML/]: Not found coremod data in tinker_io-1.10.2-release 2.4.4b.jar
[02:11:56] [main/DEBUG] [FML/]: Examining for coremod candidacy Tinkers' Addons-1.10.2-1.0.6.jar
[02:11:56] [main/DEBUG] [FML/]: Not found coremod data in Tinkers' Addons-1.10.2-1.0.6.jar
[02:11:56] [main/DEBUG] [FML/]: Examining for coremod candidacy VeinMiner-1.9-0.38.1.618+5587fc8.jar
[02:11:56] [main/DEBUG] [FML/]: Not found coremod data in VeinMiner-1.9-0.38.1.618+5587fc8.jar
[02:11:56] [main/DEBUG] [FML/]: Examining for coremod candidacy vending-1.10.2-1.4.3.jar
[02:11:56] [main/DEBUG] [FML/]: Not found coremod data in vending-1.10.2-1.4.3.jar
[02:11:56] [main/DEBUG] [FML/]: Examining for coremod candidacy VillageNames-1.10.2-2.0.jar
[02:11:56] [main/DEBUG] [FML/]: Not found coremod data in VillageNames-1.10.2-2.0.jar
[02:11:56] [main/DEBUG] [FML/]: Examining for coremod candidacy weather2-1.10.2-2.5.jar
[02:11:56] [main/DEBUG] [FML/]: Not found coremod data in weather2-1.10.2-2.5.jar
[02:11:56] [main/DEBUG] [FML/]: Examining for coremod candidacy worldedit-forge-mc1.10.2-6.1.4-dist.jar
[02:11:56] [main/DEBUG] [FML/]: Not found coremod data in worldedit-forge-mc1.10.2-6.1.4-dist.jar
[02:11:56] [main/DEBUG] [FML/]: Examining for coremod candidacy worldguard-6.2.1.jar
[02:11:56] [main/DEBUG] [FML/]: Not found coremod data in worldguard-6.2.1.jar
[02:11:56] [main/DEBUG] [FML/]: Examining for coremod candidacy zerocore-1.10.2-0.1.1.1.jar
[02:11:56] [main/DEBUG] [FML/]: Not found coremod data in zerocore-1.10.2-0.1.1.1.jar
[02:11:56] [main/INFO] [LaunchWrapper/]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[02:11:56] [main/INFO] [LaunchWrapper/]: Loading tweak class name guichaguri.betterfps.tweaker.BetterFpsTweaker
[02:11:56] [main/INFO] [LaunchWrapper/]: Loading tweak class name org.spongepowered.asm.launch.MixinTweaker
[02:11:56] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.6.15 Source=file:/home/container/mods/spongeforge-1.10.2-2477-5.2.0-BETA-2793.jar Env=SERVER
[02:11:56] [main/DEBUG] [mixin/]: Adding new mixin transformer proxy #1
[02:11:56] [main/DEBUG] [mixin/]: Initialising Mixin Platform Manager
[02:11:56] [main/DEBUG] [mixin/]: Mixin platform: primary container is file:/home/container/mods/spongeforge-1.10.2-2477-5.2.0-BETA-2793.jar
[02:11:56] [main/DEBUG] [mixin/]: Adding mixin platform agents for container file:/home/container/mods/spongeforge-1.10.2-2477-5.2.0-BETA-2793.jar
[02:11:56] [main/DEBUG] [mixin/]: Instancing new MixinPlatformAgentFML for file:/home/container/mods/spongeforge-1.10.2-2477-5.2.0-BETA-2793.jar
[02:11:56] [main/DEBUG] [mixin/]: spongeforge-1.10.2-2477-5.2.0-BETA-2793.jar has core plugin org.spongepowered.mod.SpongeCoremod. Injecting it into FML for co-initialisation:
[02:11:56] [main/DEBUG] [FML/]: Instantiating coremod class SpongeCoremod
[02:11:56] [main/DEBUG] [FML/]: The coremod org.spongepowered.mod.SpongeCoremod requested minecraft version 1.10.2 and minecraft is 1.10.2. It will be loaded.
[02:11:56] [main/INFO] [mixin/]: Compatibility level set to JAVA_8
[02:11:56] [main/INFO] [mixin/]: Adding new token provider org.spongepowered.mod.SpongeCoremod$TokenProvider to MixinEnvironment[DEFAULT]
[02:11:56] [main/INFO] [mixin/]: Adding new token provider org.spongepowered.mod.SpongeCoremod$TokenProvider to MixinEnvironment[PREINIT]
[02:11:56] [main/INFO] [mixin/]: Adding new token provider org.spongepowered.mod.SpongeCoremod$TokenProvider to MixinEnvironment[INIT]
[02:11:56] [main/DEBUG] [FML/]: Added access transformer class org.spongepowered.mod.asm.transformer.SpongeAccessTransformer to enqueued access transformers
[02:11:56] [main/DEBUG] [FML/]: Enqueued coremod SpongeCoremod
[02:11:56] [main/DEBUG] [mixin/]: Instancing new MixinPlatformAgentDefault for file:/home/container/mods/spongeforge-1.10.2-2477-5.2.0-BETA-2793.jar
[02:11:56] [main/DEBUG] [mixin/]: Scanning file:/home/container/forge-12.18.3.2511.jar for mixin tweaker
[02:11:56] [main/DEBUG] [mixin/]: Scanning file:/home/container/mods/appliedenergistics2-rv4-alpha-11.jar for mixin tweaker
[02:11:56] [main/DEBUG] [mixin/]: Scanning file:/home/container/mods/Aroma1997Core-1.9.4-1.1.1.2.jar for mixin tweaker
[02:11:56] [main/DEBUG] [mixin/]: Scanning file:/home/container/mods/ArsMagica2-1.10.2-1.5.0-17.jar for mixin tweaker
[02:11:56] [main/DEBUG] [mixin/]: Scanning file:/home/container/mods/astralsorcery-1.4.5.jar for mixin tweaker
[02:11:56] [main/DEBUG] [mixin/]: Scanning file:/home/container/mods/BetterFoliage-MC1.10.2-2.1.11.jar for mixin tweaker
[02:11:56] [main/DEBUG] [mixin/]: Scanning file:/home/container/mods/BetterFps-1.4.5-1.10.jar for mixin tweaker
[02:11:56] [main/DEBUG] [mixin/]: Scanning file:/home/container/mods/Bookshelf-1.10.2-1.4.1.320.jar for mixin tweaker
[02:11:56] [main/DEBUG] [mixin/]: Scanning file:/home/container/mods/BrandonsCore-1.10.2-2.1.14.137-universal.jar for mixin tweaker
[02:11:56] [main/DEBUG] [mixin/]: Scanning file:/home/container/mods/BuildingBricks-1.10.2-2.0.13.jar for mixin tweaker
[02:11:56] [main/DEBUG] [mixin/]: Scanning file:/home/container/mods/h3ntlibs/h3nt-commonutils-1.9.4-2.2.2.jar for mixin tweaker
[02:11:56] [main/DEBUG] [mixin/]: Scanning file:/home/container/mods/h3ntlibs/h3nt-mappings-1.1.1.jar for mixin tweaker
[02:11:56] [main/DEBUG] [mixin/]: Scanning file:/home/container/mods/h3ntlibs/h3nt-asmtweaks-1.1.1.jar for mixin tweaker
[02:11:56] [main/DEBUG] [mixin/]: Scanning file:/home/container/mods/CodeChickenLib-1.10.2-2.5.9.320-universal.jar for mixin tweaker
[02:11:56] [main/DEBUG] [mixin/]: Scanning file:/home/container/mods/CoFHCore-1.10.2.jar for mixin tweaker
[02:11:56] [main/DEBUG] [mixin/]: Scanning file:/home/container/mods/CreativeCore+v1.7.3+mc1.10.2.jar for mixin tweaker
[02:11:56] [main/DEBUG] [mixin/]: Scanning file:/home/container/mods/DynamicSurroundings-1.10.2-3.4.9.6.jar for mixin tweaker
[02:11:56] [main/DEBUG] [mixin/]: Scanning file:/home/container/mods/EnderCore-1.10.2.jar for mixin tweaker
[02:11:56] [main/DEBUG] [mixin/]: Scanning file:/home/container/mods/iceandfire-1.0.1.jar for mixin tweaker
[02:11:56] [main/DEBUG] [mixin/]: Scanning file:/home/container/mods/industrialcraft-2-2.6.252-ex110.jar for mixin tweaker
[02:11:56] [main/DEBUG] [mixin/]: Scanning file:/home/container/mods/llibrary-1.7.7-1.10.2.jar for mixin tweaker
[02:11:56] [main/DEBUG] [mixin/]: Scanning file:/home/container/mods/malisiscore-1.10.2-4.4.0.jar for mixin tweaker
[02:11:56] [main/DEBUG] [mixin/]: Scanning file:/home/container/mods/MicdoodleCore-1.10.2-4.0.1.136.jar for mixin tweaker
[02:11:56] [main/DEBUG] [mixin/]: Scanning file:/home/container/mods/NoXray.jar for mixin tweaker
[02:11:56] [main/DEBUG] [mixin/]: file:/home/container/mods/NoXray.jar contains a mixin tweaker, adding agents
[02:11:56] [main/DEBUG] [mixin/]: Adding mixin platform agents for container file:/home/container/mods/NoXray.jar
[02:11:56] [main/DEBUG] [mixin/]: Instancing new MixinPlatformAgentFML for file:/home/container/mods/NoXray.jar
[02:11:56] [main/DEBUG] [mixin/]: ForceLoadAsMod was specified for NoXray.jar, attempting force-load
[02:11:56] [main/DEBUG] [mixin/]: Instancing new MixinPlatformAgentDefault for file:/home/container/mods/NoXray.jar
[02:11:56] [main/DEBUG] [mixin/]: Scanning file:/home/container/mods/OpenModsLib-1.10.2-0.11.5.jar for mixin tweaker
[02:11:56] [main/DEBUG] [mixin/]: Scanning file:/home/container/mods/OptiFine_1.10.2_HD_U_D4.jar for mixin tweaker
[02:11:56] [main/DEBUG] [mixin/]: Scanning file:/home/container/mods/RandomThings-MC1.10.2-3.7.7.1.jar for mixin tweaker
[02:11:56] [main/DEBUG] [mixin/]: Scanning file:/home/container/mods/ResourceLoader-MC1.9.4-1.5.1.jar for mixin tweaker
[02:11:56] [main/INFO] [LaunchWrapper/]: Loading tweak class name optifine.OptiFineForgeTweaker
[02:11:56] [main/WARN] [LaunchWrapper/]: Tweak class name org.spongepowered.asm.launch.MixinTweaker has already been visited -- skipping
[02:11:56] [main/INFO] [LaunchWrapper/]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[02:11:56] [main/INFO] [LaunchWrapper/]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[02:11:56] [main/INFO] [LaunchWrapper/]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[02:11:56] [main/INFO] [LaunchWrapper/]: Calling tweak class optifine.OptiFineForgeTweaker
[02:11:56] [main/INFO] [STDOUT/]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: acceptOptions
[02:11:56] [main/INFO] [STDOUT/]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: Forge server detected, skipping class transformer
[02:11:56] [main/INFO] [LaunchWrapper/]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[02:11:56] [main/DEBUG] [FML/]: Injecting coremod FMLCorePlugin {net.minecraftforge.fml.relauncher.FMLCorePlugin} class transformers
[02:11:56] [main/TRACE] [FML/]: Registering transformer net.minecraftforge.fml.common.asm.transformers.BlamingTransformer
[02:11:56] [main/DEBUG] [mixin/]: Preparing mixins for MixinEnvironment[PREINIT]
[02:11:56] [main/DEBUG] [mixin/]: Selecting config mixins.forge.preinit.json
[02:11:56] [main/DEBUG] [mixin/]: Preparing mixins.forge.preinit.json (9)
[02:11:56] [main/DEBUG] [mixin/]: Rebuilding transformer delegation list:
[02:11:56] [main/DEBUG] [mixin/]:   Adding:    net.minecraftforge.fml.common.asm.transformers.PatchingTransformer
[02:11:56] [main/DEBUG] [mixin/]:   Excluding: org.spongepowered.asm.mixin.transformer.MixinTransformer$Proxy
[02:11:56] [main/DEBUG] [mixin/]: Transformer delegation list created with 1 entries
[02:11:56] [main/TRACE] [mixin/]: Added class metadata for net/minecraftforge/common/UsernameCache to metadata cache
[02:11:56] [main/TRACE] [mixin/]: Added class metadata for net/minecraftforge/fml/common/Loader to metadata cache
[02:11:56] [main/TRACE] [mixin/]: Added class metadata for net/minecraftforge/fml/common/LoadController to metadata cache
[02:11:56] [main/INFO] [mixin/]: Instancing error handler class org.spongepowered.mod.mixin.handler.MixinErrorHandler
[02:11:56] [main/INFO] [Sponge/]: /******************************************************************************************************************************************************************************/
[02:11:56] [main/INFO] [Sponge/]: /*                                                                                                                                                                            */
[02:11:56] [main/INFO] [Sponge/]: /* Oh dear. Sponge could not apply one or more patches. A required class was loaded prematurely!                                                                              */
[02:11:56] [main/INFO] [Sponge/]: /*                                                                                                                                                                            */
[02:11:56] [main/INFO] [Sponge/]: /*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
[02:11:56] [main/INFO] [Sponge/]: /*                                                                                                                                                                            */
[02:11:56] [main/INFO] [Sponge/]: /* An essential class was loaded before Sponge could patch it, this usually means                                                                                             */
[02:11:56] [main/INFO] [Sponge/]: /* that another coremod has caused the class to load prematurely.                                                                                                             */
[02:11:56] [main/INFO] [Sponge/]: /*                                                                                                                                                                            */
[02:11:56] [main/INFO] [Sponge/]: /*           Class Name : net.minecraftforge.fml.common.ModContainer                                                                                                          */
[02:11:56] [main/INFO] [Sponge/]: /*                                                                                                                                                                            */
[02:11:56] [main/INFO] [Sponge/]: /*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
[02:11:56] [main/INFO] [Sponge/]: /*                                                                                                                                                                            */
[02:11:56] [main/INFO] [Sponge/]: /* Loaded forge classes:                                                                                                                                                      */
[02:11:56] [main/INFO] [Sponge/]: /*                                                                                                                                                                            */
[02:11:56] [main/INFO] [Sponge/]: /*     net.minecraftforge.fml.common.DummyModContainer                                                                                                                        */
[02:11:56] [main/INFO] [Sponge/]: /*     net.minecraftforge.fml.repackage.com.nothome.delta.GDiffPatcher                                                                                                        */
[02:11:56] [main/INFO] [Sponge/]: /*     net.minecraftforge.fml.common.ModMetadata                                                                                                                              */
[02:11:56] [main/INFO] [Sponge/]: /*     net.minecraftforge.fml.repackage.com.nothome.delta.PatchException                                                                                                      */
[02:11:56] [main/INFO] [Sponge/]: /*     net.minecraftforge.fml.common.versioning.ComparableVersion$ListItem                                                                                                    */
[02:11:56] [main/INFO] [Sponge/]: /*     net.minecraftforge.fml.common.patcher.ClassPatchManager                                                                                                                */
[02:11:56] [main/INFO] [Sponge/]: /*     net.minecraftforge.fml.common.asm.transformers.PatchingTransformer                                                                                                     */
[02:11:56] [main/INFO] [Sponge/]: /*     net.minecraftforge.fml.common.versioning.ComparableVersion                                                                                                             */
[02:11:56] [main/INFO] [Sponge/]: /*     net.minecraftforge.fml.common.versioning.ComparableVersion$Item                                                                                                        */
[02:11:56] [main/INFO] [Sponge/]: /*     net.minecraftforge.fml.repackage.com.nothome.delta.SeekableSource                                                                                                      */
[02:11:56] [main/INFO] [Sponge/]: /*     net.minecraftforge.fml.common.LoaderException                                                                                                                          */
[02:11:56] [main/INFO] [Sponge/]: /*     net.minecraftforge.fml.common.FMLLog                                                                                                                                   */
[02:11:56] [main/INFO] [Sponge/]: /*     net.minecraftforge.fml.common.versioning.ArtifactVersion                                                                                                               */
[02:11:56] [main/INFO] [Sponge/]: /*     net.minecraftforge.fml.common.versioning.ComparableVersion$IntegerItem                                                                                                 */
[02:11:56] [main/INFO] [Sponge/]: /*     net.minecraftforge.fml.common.ModContainer                                                                                                                             */
[02:11:56] [main/INFO] [Sponge/]: /*     net.minecraftforge.fml.common.EnhancedRuntimeException                                                                                                                 */
[02:11:56] [main/INFO] [Sponge/]: /*                                                                                                                                                                            */
[02:11:56] [main/INFO] [Sponge/]: /*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
[02:11:56] [main/INFO] [Sponge/]: /*                                                                                                                                                                            */
[02:11:56] [main/INFO] [Sponge/]: /* Technical details:                                                                                                                                                         */
[02:11:56] [main/INFO] [Sponge/]: /*                                                                                                                                                                            */
[02:11:56] [main/INFO] [Sponge/]: /*      Failed on class : net.minecraftforge.fml.common.ModContainer                                                                                                          */
[02:11:56] [main/INFO] [Sponge/]: /*         During phase : PREINIT                                                                                                                                             */
[02:11:56] [main/INFO] [Sponge/]: /*                Mixin : fml.common.MixinModContainer                                                                                                                        */
[02:11:56] [main/INFO] [Sponge/]: /*               Config : mixins.forge.preinit.json                                                                                                                           */
[02:11:56] [main/INFO] [Sponge/]: /*           Error Type : org.spongepowered.asm.mixin.transformer.throwables.MixinTargetAlreadyLoadedException                                                                */
[02:11:56] [main/INFO] [Sponge/]: /*            Caused by : Unknown                                                                                                                                             */
[02:11:56] [main/INFO] [Sponge/]: /*              Message : Critical problem: mixins.forge.preinit.json:fml.common.MixinModContainer target net.minecraftforge.fml.common.ModContainer was already transformed. */
[02:11:56] [main/INFO] [Sponge/]: /*                                                                                                                                                                            */
[02:11:56] [main/INFO] [Sponge/]: /******************************************************************************************************************************************************************************/
[02:11:56] [main/INFO] [Sponge/]: Attempting to shut down the VM cleanly
[02:11:56] [main/INFO] [FML/]: Java has been asked to exit (code -1) by net.minecraftforge.fml.common.FMLCommonHandler.exitJava(FMLCommonHandler.java:656).
[02:11:56] [main/INFO] [FML/]: This is an abortive exit and could cause world corruption or other things
[02:11:56] [main/INFO] [FML/]: If this was an unexpected exit, use -Dfml.debugExit=true as a JVM argument to find out where it was called
[02:11:56] [main/INFO] [Sponge/]: Clean shutdown failed, forcing VM termination
