### ISSUE TITLE
Server Crash - elec332.core.grid.v2.AbstractGridHandler.checkChunkLoad(AbstractGridHandler.java:171)

### ISSUE THREAD

**Issue by ProsperCraft** [SpongePowered/SpongeForge#992]
https://github.com/Elecs-Mods/ElecCore/issues/65#issuecomment-256422978

This server crash does not occur with sponge disabled.

**Comment by ProsperCraft** [comment]
Then I re-enabled sponge and he was able to log in....so may not be clearly sponge.

**Comment by ProsperCraft** [comment]
Please re-open, mod author is pointing back here.

**Comment by simon816** [comment]
I need exact steps to reproduce this otherwise I can't investigate,

**Comment by ProsperCraft** [comment]
There are no steps, certain players log in and the server crashes...we disable sponge and it doesn't

**Comment by ProsperCraft** [comment]
Also once the server starts crashing due to this issue, it happens every time they log in.

But...once you disable sponge, let them log in, then re-enable sponge they can log in without crashing the server.

**Comment by gabizou** [comment]
Can you provide some of the latest crash logs? Also is it only with ElecCore?

**Comment by LemADEC** [comment]
Please remove the link once you've downloaded it

**Comment by ProsperCraft** [comment]
Latest crash logs are found here-
https://github.com/Elecs-Mods/ElecCore/issues/65#issuecomment-256422978

**Comment by bloodmc** [comment]
This issue was fixed by dev. Upload to latest ElecCore builds. Also make sure you are running LATEST SF builds.

**Comment by Elec332** [comment]
Amazing to hear this issue has been fixed! Great job SP team!

**Comment by Aaron1011** [comment]
This is still an issue on the latest SpongeForge.

**Comment by john01dav** [comment]
@Aaron1011 When I switch to your build and update Sponge to the latest recommended version, the error goes away. Thanks :)

**Comment by Aaron1011** [comment]
For reference, here's my comment from the other issue:


@john01dav @Dongonzales: Try using [this build](https://www.dropbox.com/s/m5jvo1o6n5wph0t/ElecCore-1.10.2-1.6.localBuild-fake-1.6.345.jar?dl=0) (Source at https://github.com/Aaron1011/ElecCore/commit/9b04dae02808b7740d8fa4fd53eb7063d7cb6b28). I've added some extra information to the exception being printed out, which should help to debug this.

I'm almost certain that this is a Sponge issue, as I've talked t several other people who've been experiencing it. We should continue the discussion here: https://github.com/SpongePowered/SpongeForge/issues/992

**Comment by Aaron1011** [comment]
@john01dav: My build actually doesn't fix anything 😄 - all it does it add more information to the errors printed out during a crash. If the crash comes up again, can you post the new crash report here?

**Comment by Mohron** [comment]
I'm experiencing this issue. If it helps, here's a bugged inv and a fixed inv. They're different by 1 byte but i couldn't see the difference using nbt explorer either.
[BUGGED](https://dl.dropboxusercontent.com/u/27532718/Inventories/7ae0b839-d948-4db5-b2c9-147ff83264cf.dat.bad)
[FIXED](https://dl.dropboxusercontent.com/u/27532718/Inventories/7ae0b839-d948-4db5-b2c9-147ff83264cf.dat)

**Comment by Aaron1011** [comment]
@Mohron: Can you post the crash log you get when using my build?

**Comment by Mohron** [comment]
@Aaron1011 I already fixed the crashing player, this had happened multiple times before so I was able to deal with it quickly. If it's the same elecCore I can wait for it to happen again or you can just run SpongeForge with DW20 1.2.1 and make the bad inventory your own.

**Comment by Aaron1011** [comment]
@Mohron: Would you be able to join `#spongedev` on `irc.esper.net` to discuss this further?

**Comment by KasperFranz** [comment]
@Aaron1011 
here is my crash-log, after using your build :) 

```

java.lang.IllegalStateException: Some chunkcheck failed! Instance: mcjty.deepresonance.tanks.TankGridHandler@9484cd1 mcjty.deepresonance.tanks.TankGridHandler Position: [DimensionCoordinate: BlockPos{x=-562, y=56, z=810} dim: 0] Object: mcjty.deepresonance.tanks.TankTileLink@199cc88c TileEntity: mcjty.deepresonance.blocks.tank.TileTank@183b6bf9 oldUpdates: [[DimensionCoordinate: BlockPos{x=-562, y=56, z=810} dim: 0], [DimensionCoordinate: BlockPos{x=-562, y=58, z=810} dim: 0], [DimensionCoordinate: BlockPos{x=-562, y=58, z=807} dim: 0], [DimensionCoordinate: BlockPos{x=-562, y=56, z=806} dim: 0], [DimensionCoordinate: BlockPos{x=-562, y=56, z=807} dim: 0], [DimensionCoordinate: BlockPos{x=-562, y=56, z=813} dim: 0]] add: [] changeCheck: [] updates: [[DimensionCoordinate: BlockPos{x=-562, y=56, z=810} dim: 0], [DimensionCoordinate: BlockPos{x=-562, y=58, z=810} dim: 0], [DimensionCoordinate: BlockPos{x=-562, y=58, z=807} dim: 0], [DimensionCoordinate: BlockPos{x=-562, y=56, z=806} dim: 0], [DimensionCoordinate: BlockPos{x=-562, y=56, z=807} dim: 0], [DimensionCoordinate: BlockPos{x=-562, y=56, z=813} dim: 0]] dimCoord: [DimensionCoordinate: BlockPos{x=-562, y=56, z=810} dim: 0]
	at elec332.core.grid.AbstractGridHandler.checkChunkLoad(AbstractGridHandler.java:176)
	at elec332.core.grid.internal.GridEventInputHandler.tickEnd(GridEventInputHandler.java:108)
	at elec332.core.grid.internal.GridEventHandler.serverTick(GridEventHandler.java:49)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_249_GridEventHandler_serverTick_ServerTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:137)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:93)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:261)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:657)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by Aaron1011** [comment]
@KasperFranz: Does this issue occur when a player logs in near the location mentioned in the error? If so, can you screenshot the tank setup at that location?

**Comment by KasperFranz** [comment]
it happens if a player goes near it/logs in near it.

Only got a screenshot with the removed block - gonna find it and attach it 
http://puu.sh/t5BuX/52d8ea33ec.png

it seems to only be if certain people go near it (I am as confused as you are)

**Comment by curscascis** [comment]
I am currently experiencing this same issue. Will test with Aaron's build and post my report.

**Comment by curscascis** [comment]
I am running DW 1.2.2
`java.lang.IllegalStateException: Some chunkcheck failed! Instance: mcjty.deepresonance.tanks.TankGridHandler@51285273 mcjty.deepresonance.tanks.TankGridHandler Position: [DimensionCoordinate: BlockPos{x=-5661, y=25, z=19223} dim: 0] Object: mcjty.deepresonance.tanks.TankTileLink@1882a264 TileEntity: mcjty.deepresonance.blocks.tank.TileTank@5afa1877 oldUpdates: [[DimensionCoordinate: BlockPos{x=-5661, y=25, z=19223} dim: 0], [DimensionCoordinate: BlockPos{x=-5660, y=25, z=19222} dim: 0], [DimensionCoordinate: BlockPos{x=-5661, y=24, z=19223} dim: 0], [DimensionCoordinate: BlockPos{x=-5659, y=25, z=19223} dim: 0], [DimensionCoordinate: BlockPos{x=-5658, y=25, z=19222} dim: 0], [DimensionCoordinate: BlockPos{x=-5659, y=24, z=19223} dim: 0], [DimensionCoordinate: BlockPos{x=-5659, y=23, z=19223} dim: 0], [DimensionCoordinate: BlockPos{x=-5657, y=25, z=19223} dim: 0], [DimensionCoordinate: BlockPos{x=-5656, y=25, z=19222} dim: 0], [DimensionCoordinate: BlockPos{x=-5657, y=24, z=19223} dim: 0], [DimensionCoordinate: BlockPos{x=-5657, y=23, z=19223} dim: 0], [DimensionCoordinate: BlockPos{x=-5668, y=25, z=19223} dim: 0], [DimensionCoordinate: BlockPos{x=-5668, y=24, z=19223} dim: 0], [DimensionCoordinate: BlockPos{x=-5666, y=25, z=19223} dim: 0], [DimensionCoordinate: BlockPos{x=-5668, y=23, z=19223} dim: 0], [DimensionCoordinate: BlockPos{x=-5664, y=25, z=19223} dim: 0], [DimensionCoordinate: BlockPos{x=-5663, y=25, z=19222} dim: 0], [DimensionCoordinate: BlockPos{x=-5664, y=24, z=19223} dim: 0], [DimensionCoordinate: BlockPos{x=-5662, y=25, z=19223} dim: 0], [DimensionCoordinate: BlockPos{x=-5661, y=25, z=19222} dim: 0], [DimensionCoordinate: BlockPos{x=-5662, y=24, z=19223} dim: 0], [DimensionCoordinate: BlockPos{x=-5660, y=25, z=19223} dim: 0], [DimensionCoordinate: BlockPos{x=-5659, y=25, z=19222} dim: 0], [DimensionCoordinate: BlockPos{x=-5660, y=24, z=19223} dim: 0], [DimensionCoordinate: BlockPos{x=-5658, y=25, z=19223} dim: 0], [DimensionCoordinate: BlockPos{x=-5657, y=25, z=19222} dim: 0], [DimensionCoordinate: BlockPos{x=-5656, y=25, z=19223} dim: 0], [DimensionCoordinate: BlockPos{x=-5656, y=24, z=19223} dim: 0], [DimensionCoordinate: BlockPos{x=-5656, y=23, z=19223} dim: 0], [DimensionCoordinate: BlockPos{x=-5667, y=25, z=19223} dim: 0], [DimensionCoordinate: BlockPos{x=-5667, y=24, z=19223} dim: 0], [DimensionCoordinate: BlockPos{x=-5665, y=25, z=19223} dim: 0], [DimensionCoordinate: BlockPos{x=-5667, y=23, z=19223} dim: 0], [DimensionCoordinate: BlockPos{x=-5664, y=25, z=19222} dim: 0], [DimensionCoordinate: BlockPos{x=-5665, y=24, z=19223} dim: 0], [DimensionCoordinate: BlockPos{x=-5663, y=25, z=19223} dim: 0], [DimensionCoordinate: BlockPos{x=-5662, y=25, z=19222} dim: 0]] add: [] changeCheck: [] updates: [[DimensionCoordinate: BlockPos{x=-5661, y=25, z=19223} dim: 0], [DimensionCoordinate: BlockPos{x=-5660, y=25, z=19222} dim: 0], [DimensionCoordinate: BlockPos{x=-5661, y=24, z=19223} dim: 0], [DimensionCoordinate: BlockPos{x=-5659, y=25, z=19223} dim: 0], [DimensionCoordinate: BlockPos{x=-5658, y=25, z=19222} dim: 0], [DimensionCoordinate: BlockPos{x=-5659, y=24, z=19223} dim: 0], [DimensionCoordinate: BlockPos{x=-5659, y=23, z=19223} dim: 0], [DimensionCoordinate: BlockPos{x=-5657, y=25, z=19223} dim: 0], [DimensionCoordinate: BlockPos{x=-5656, y=25, z=19222} dim: 0], [DimensionCoordinate: BlockPos{x=-5657, y=24, z=19223} dim: 0], [DimensionCoordinate: BlockPos{x=-5657, y=23, z=19223} dim: 0], [DimensionCoordinate: BlockPos{x=-5668, y=25, z=19223} dim: 0], [DimensionCoordinate: BlockPos{x=-5668, y=24, z=19223} dim: 0], [DimensionCoordinate: BlockPos{x=-5666, y=25, z=19223} dim: 0], [DimensionCoordinate: BlockPos{x=-5668, y=23, z=19223} dim: 0], [DimensionCoordinate: BlockPos{x=-5664, y=25, z=19223} dim: 0], [DimensionCoordinate: BlockPos{x=-5663, y=25, z=19222} dim: 0], [DimensionCoordinate: BlockPos{x=-5664, y=24, z=19223} dim: 0], [DimensionCoordinate: BlockPos{x=-5662, y=25, z=19223} dim: 0], [DimensionCoordinate: BlockPos{x=-5661, y=25, z=19222} dim: 0], [DimensionCoordinate: BlockPos{x=-5662, y=24, z=19223} dim: 0], [DimensionCoordinate: BlockPos{x=-5660, y=25, z=19223} dim: 0], [DimensionCoordinate: BlockPos{x=-5659, y=25, z=19222} dim: 0], [DimensionCoordinate: BlockPos{x=-5660, y=24, z=19223} dim: 0], [DimensionCoordinate: BlockPos{x=-5658, y=25, z=19223} dim: 0], [DimensionCoordinate: BlockPos{x=-5657, y=25, z=19222} dim: 0], [DimensionCoordinate: BlockPos{x=-5656, y=25, z=19223} dim: 0], [DimensionCoordinate: BlockPos{x=-5656, y=24, z=19223} dim: 0], [DimensionCoordinate: BlockPos{x=-5656, y=23, z=19223} dim: 0], [DimensionCoordinate: BlockPos{x=-5667, y=25, z=19223} dim: 0], [DimensionCoordinate: BlockPos{x=-5667, y=24, z=19223} dim: 0], [DimensionCoordinate: BlockPos{x=-5665, y=25, z=19223} dim: 0], [DimensionCoordinate: BlockPos{x=-5667, y=23, z=19223} dim: 0], [DimensionCoordinate: BlockPos{x=-5664, y=25, z=19222} dim: 0], [DimensionCoordinate: BlockPos{x=-5665, y=24, z=19223} dim: 0], [DimensionCoordinate: BlockPos{x=-5663, y=25, z=19223} dim: 0], [DimensionCoordinate: BlockPos{x=-5662, y=25, z=19222} dim: 0]] dimCoord: [DimensionCoordinate: BlockPos{x=-5661, y=25, z=19223} dim: 0]
	at elec332.core.grid.AbstractGridHandler.checkChunkLoad(AbstractGridHandler.java:176)
	at elec332.core.grid.internal.GridEventInputHandler.tickEnd(GridEventInputHandler.java:108)
	at elec332.core.grid.internal.GridEventHandler.serverTick(GridEventHandler.java:49)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_301_GridEventHandler_serverTick_ServerTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:137)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:93)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:261)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:657)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)
`

**Comment by curscascis** [comment]
https://i.imgur.com/0qdTLkY.png
This is a screenshot of the base causing it. I used world edit to replace the area with lava and then undid it, people can now go there without it crashing.

@Aaron1011 
I'd like to point out that this only happened after deleting forcedchunks.dat earlier today. I can not say if it was a coincidence or not, but seeing the stack, I think it might be related.

**Comment by Aaron1011** [comment]
The root of this issue is that `Chunk#onChunLload` was being called twice for the same chunk - once from Forge's async chunk loader code, and once from Sponge's `loadChunkForce` method. This caused a `ChunkEVent.Load` to be fired twice for the same chunk, messing up ElecCore (along with any number of other things).

Sponge's `loadChunkForce` method was intended to bypass an unecessary check found n the Vanilla `loadChunk` method. However, Forge modifies `loadChunk` extensively, so we need to delgate to Forge's modified method in SpongeForge.

The latest SpongeForge has a fix for this issue.

**Comment by Eufranio** [comment]
❤️
