### ISSUE TITLE
Players unable to log in to a world that is unloaded

### ISSUE THREAD

**Issue by ProsperCraft** [SpongePowered/SpongeForge#995]
https://github.com/NucleusPowered/Nucleus/issues/449

**Comment by bloodmc** [comment]
@ProsperCraft fixed in latest build.

**Comment by ProsperCraft** [comment]
This is still an issue with 1853

**Comment by bloodmc** [comment]
@ProsperCraft Remove all mods/plugins EXCEPT Sponge/Nucleus and retest.
1. /world create myworld
2. /world teleport myworld
3. Disconnect
4. /world unload myworld
5. Reconnect
   Works as expected

**Comment by ProsperCraft** [comment]
Verified that it still happens when plugins are disabled entirely and only sponge.  
Doing your next steps now.

**Comment by ProsperCraft** [comment]
I had no problems logging in after the world was unloaded.

Deleting spongeconfigs for the world the player can't log in to and letting them regen.

**Comment by ProsperCraft** [comment]
Still can't log in if you log out in the gather world which was created pre sponge fix.

Tomorrow we are scheduled to wipe that world so we will recreate it then.

**Comment by ProsperCraft** [comment]
So here is something odd, I bet this will help.

When this happens you actually log into the game, other players can see you, but your client still says "Logging in..."

I had a player teleport to me in the gather world and they can see me, yet I still can't log in.  

So perhaps not a chunk loading issue?

**Comment by ProsperCraft** [comment]
Still having this issue with a world created with 

```
SpongeAPI: 6.0.0-SNAPSHOT-f247c80
SpongeForge: 1.10.2-2107-6.0.0-BETA-1862
Minecraft Forge: 12.18.2.2114
```

**Comment by ProsperCraft** [comment]
This is a gamebreaking issue please re-open.

**Comment by Deamon5550** [comment]
Start removing mods to find out which one is causing this, because as stated above it works fine with just sponge.

**Comment by bloodmc** [comment]
Fixed in latest. SpongeCommon commit can be found here
https://github.com/SpongePowered/SpongeCommon/commit/dbf3c828d24cba094ef118b6e5aa1086a3db2b17

**Comment by ProsperCraft** [comment]
SO HAPPY!!!  Thank you
